/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminServiceZone } from './admin-service-zone';


/**
 * The service zone\'s details.
 */
export interface AdminServiceZoneResponse { 
    service_zone: AdminServiceZone;
}

