/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The tax region\'s details.
 */
export interface AdminTaxRegion { 
    /**
     * The tax region\'s ID.
     */
    id: string;
    /**
     * The tax region\'s country code.
     */
    country_code: string;
    /**
     * The tax region\'s province code.
     */
    province_code: string;
    /**
     * The tax region\'s metadata, can hold custom key-value pairs.
     */
    metadata: object;
    /**
     * The ID of the parent tax region.
     */
    parent_id: string;
    /**
     * The date the tax region was created.
     */
    created_at: string;
    /**
     * The date the tax region was updated.
     */
    updated_at: string;
    /**
     * The date the tax region was deleted.
     */
    deleted_at: string;
    /**
     * The ID of the user that created the tax region.
     */
    created_by: string;
    /**
     * The tax region\'s rates.
     */
    tax_rates: Array<object>;
    parent: object;
    /**
     * The tax region\'s children.
     */
    children: Array<object>;
}

