/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The details of the received item.
 */
export interface AdminPostReturnsReceiveItemsActionReqSchema { 
    /**
     * The item\'s quantity.
     */
    quantity?: number;
    /**
     * A note viewed only by admin users.
     */
    internal_note?: string;
}

