/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminInventoryItem } from './admin-inventory-item';


/**
 * The inventory item\'s details.
 */
export interface AdminInventoryItemResponse { 
    inventory_item: AdminInventoryItem;
}

