/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The details of the variant-inventory item association.
 */
export interface AdminCreateVariantInventoryItem { 
    /**
     * The quantity of the variant in the inventory item.
     */
    required_quantity: number;
    /**
     * The inventory item\'s ID.
     */
    inventory_item_id: string;
}

