/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The API key\'s details.
 */
export interface AdminCreateApiKey { 
    /**
     * The API key\'s title.
     */
    title: string;
    /**
     * The API key\'s type. Use `secret` for a user\'s API key; Use `publishable` for Publishable API keys.
     */
    type: AdminCreateApiKey.TypeEnum;
}
export namespace AdminCreateApiKey {
    export type TypeEnum = 'publishable' | 'secret';
    export const TypeEnum = {
        Publishable: 'publishable' as TypeEnum,
        Secret: 'secret' as TypeEnum
    };
}


