/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminShippingOption } from './admin-shipping-option';


/**
 * The shipping option\'s details.
 */
export interface AdminShippingOptionResponse { 
    shipping_option: AdminShippingOption;
}

