/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminFile } from './admin-file';


/**
 * The list of uploaded files.
 */
export interface AdminFileListResponse { 
    /**
     * The list of uploaded files.
     */
    files: Array<AdminFile>;
}

