/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminReturnReason } from './admin-return-reason';


/**
 * The return reason\'s details.
 */
export interface AdminReturnReasonResponse { 
    return_reason: AdminReturnReason;
}

