/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The details of an inventory level to create.
 */
export interface AdminBatchCreateInventoryItemsLocationLevels { 
    /**
     * The ID of the associated stock location.
     */
    location_id: string;
    /**
     * The ID of the associated inventory item.
     */
    inventory_item_id: string;
    /**
     * The stocked quantity.
     */
    stocked_quantity?: number;
    /**
     * The incoming quantity to be added to stock.
     */
    incoming_quantity?: number;
}

