/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A shipment\'s label.
 */
export interface AdminCreateFulfillmentLabelsInner { 
    /**
     * The label\'s tracking number.
     */
    tracking_number: string;
    /**
     * The label\'s tracking URL.
     */
    tracking_url: string;
    /**
     * The label\'s URL.
     */
    label_url: string;
}

