/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminShippingProfile } from './admin-shipping-profile';


/**
 * The shipping profile\'s details.
 */
export interface AdminShippingProfileResponse { 
    shipping_profile: AdminShippingProfile;
}

