/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminOrderChange } from './admin-order-change';


/**
 * An order edit\'s details.
 */
export interface AdminOrderEditResponse { 
    order_change: AdminOrderChange;
}

