/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An item to fulfill.
 */
export interface AdminCreateFulfillmentItemsInner { 
    /**
     * The item\'s title.
     */
    title: string;
    /**
     * The item\'s SKU.
     */
    sku: string;
    /**
     * The quantity to fulfill of the item.
     */
    quantity: number;
    /**
     * The item\'s barcode.
     */
    barcode: string;
    /**
     * The ID of the associated line item.
     */
    line_item_id?: string;
    /**
     * The ID of the inventory item associated with the underlying variant.
     */
    inventory_item_id?: string;
}

