/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminCreateProduct } from './admin-create-product';
import { AdminBatchUpdateProduct } from './admin-batch-update-product';


/**
 * The products to create, update, or delete.
 */
export interface AdminBatchProductRequest { 
    /**
     * The products to create.
     */
    create?: Array<AdminCreateProduct>;
    /**
     * The products to update.
     */
    update?: Array<AdminBatchUpdateProduct>;
    /**
     * The products to delete.
     */
    'delete'?: Array<string>;
}

