/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * @type AdminOrderPreviewShippingMethodsInnerAllOfOriginalTaxTotal
 * @export
 */
export type AdminOrderPreviewShippingMethodsInnerAllOfOriginalTaxTotal = number | string;

