/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminShippingOption } from './admin-shipping-option';
import { AdminGeoZone } from './admin-geo-zone';


/**
 * The shipping option\'s service zone.
 */
export interface AdminServiceZone { 
    /**
     * The service zone\'s ID.
     */
    id: string;
    /**
     * The service zone\'s name.
     */
    name: string;
    /**
     * The service zone\'s fulfillment set id.
     */
    fulfillment_set_id: string;
    fulfillment_set: object;
    /**
     * The service zone\'s geo zones.
     */
    geo_zones: Array<AdminGeoZone>;
    /**
     * The service zone\'s shipping options.
     */
    shipping_options: Array<AdminShippingOption>;
    /**
     * The service zone\'s created at.
     */
    created_at: string;
    /**
     * The service zone\'s updated at.
     */
    updated_at: string;
    /**
     * The service zone\'s deleted at.
     */
    deleted_at: string;
}

