/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The details of the shipping method to update.
 */
export interface AdminPostExchangesShippingActionReqSchema { 
    /**
     * The shipping method\'s custom amount.
     */
    custom_amount?: number;
    /**
     * A note viewed by admin users only.
     */
    internal_note?: string;
    /**
     * The exchange\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
}

