/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminFulfillmentSet } from './admin-fulfillment-set';


/**
 * The details of the service zone deletion.
 */
export interface AdminServiceZoneDeleteResponse { 
    /**
     * The service zone\'s ID.
     */
    id: string;
    /**
     * The name of the deleted object.
     */
    object: string;
    /**
     * Whether the service zone was deleted.
     */
    deleted: boolean;
    parent?: AdminFulfillmentSet;
}

