/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The price rule\'s value.
 */
/**
 * @type AdminShippingOptionPriceRuleValue
 * The price rule\'s value.
 * @export
 */
export type AdminShippingOptionPriceRuleValue = number | string;

