/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminPostReturnsRequestItemsReqSchemaItemsInner } from './admin-post-returns-request-items-req-schema-items-inner';


/**
 * The items\' details.
 */
export interface AdminPostReturnsRequestItemsReqSchema { 
    /**
     * The items\' details.
     */
    items?: Array<AdminPostReturnsRequestItemsReqSchemaItemsInner>;
}

