/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminCreateShippingOptionRuleValue } from './admin-create-shipping-option-rule-value';


/**
 * The details of the shipping option rule.
 */
export interface AdminCreateShippingOptionRule { 
    /**
     * The operator used to check whether a rule applies.
     */
    operator: AdminCreateShippingOptionRule.OperatorEnum;
    /**
     * The name of a property or table that the rule applies to.
     */
    attribute: string;
    value: AdminCreateShippingOptionRuleValue;
}
export namespace AdminCreateShippingOptionRule {
    export type OperatorEnum = 'gt' | 'lt' | 'eq' | 'ne' | 'in' | 'lte' | 'gte' | 'nin';
    export const OperatorEnum = {
        Gt: 'gt' as OperatorEnum,
        Lt: 'lt' as OperatorEnum,
        Eq: 'eq' as OperatorEnum,
        Ne: 'ne' as OperatorEnum,
        In: 'in' as OperatorEnum,
        Lte: 'lte' as OperatorEnum,
        Gte: 'gte' as OperatorEnum,
        Nin: 'nin' as OperatorEnum
    };
}


