/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The return\'s details.
 */
export interface AdminPostReturnsReturnReqSchema { 
    /**
     * The ID of the location to return items to.
     */
    location_id?: string;
    /**
     * Whether the customer should receive notifications about updates to the return.
     */
    no_notification?: boolean;
    /**
     * The return\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
}

