/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The claim\'s details.
 */
export interface AdminPostOrderClaimsReqSchema { 
    /**
     * The claim\'s type.
     */
    type: AdminPostOrderClaimsReqSchema.TypeEnum;
    /**
     * The ID of the order the claim is created for.
     */
    order_id: string;
    /**
     * The claim\'s description.
     */
    description?: string;
    /**
     * A note viewed only by admin users.
     */
    internal_note?: string;
    /**
     * The ID of the associated return reason.
     */
    reason_id?: string;
    /**
     * The claim\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
}
export namespace AdminPostOrderClaimsReqSchema {
    export type TypeEnum = 'refund' | 'replace';
    export const TypeEnum = {
        Refund: 'refund' as TypeEnum,
        Replace: 'replace' as TypeEnum
    };
}


