/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * the details to update in a price list.
 */
export interface AdminUpdatePriceList { 
    /**
     * The price list\'s title.
     */
    title?: string;
    /**
     * The price list\'s description.
     */
    description?: string;
    /**
     * The date the price list starts.
     */
    starts_at?: string;
    /**
     * The date the price list ends.
     */
    ends_at?: string;
    /**
     * The price list\'s status.
     */
    status?: AdminUpdatePriceList.StatusEnum;
    /**
     * The price list\'s type.
     */
    type?: AdminUpdatePriceList.TypeEnum;
    /**
     * The price list\'s rules.
     */
    rules?: object;
}
export namespace AdminUpdatePriceList {
    export type StatusEnum = 'active' | 'draft';
    export const StatusEnum = {
        Active: 'active' as StatusEnum,
        Draft: 'draft' as StatusEnum
    };
    export type TypeEnum = 'sale' | 'override';
    export const TypeEnum = {
        Sale: 'sale' as TypeEnum,
        Override: 'override' as TypeEnum
    };
}


