/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The state of the step\'s invokation function.
 */
export interface AdminWorkflowExecutionExecutionStepsValueInvoke { 
    /**
     * The invokation step\'s state.
     */
    state: AdminWorkflowExecutionExecutionStepsValueInvoke.StateEnum;
    /**
     * The invokation step\'s state.
     */
    status: AdminWorkflowExecutionExecutionStepsValueInvoke.StatusEnum;
}
export namespace AdminWorkflowExecutionExecutionStepsValueInvoke {
    export type StateEnum = 'not_started' | 'invoking' | 'compensating' | 'done' | 'reverted' | 'failed' | 'dormant' | 'skipped' | 'skipped_failure' | 'timeout';
    export const StateEnum = {
        NotStarted: 'not_started' as StateEnum,
        Invoking: 'invoking' as StateEnum,
        Compensating: 'compensating' as StateEnum,
        Done: 'done' as StateEnum,
        Reverted: 'reverted' as StateEnum,
        Failed: 'failed' as StateEnum,
        Dormant: 'dormant' as StateEnum,
        Skipped: 'skipped' as StateEnum,
        SkippedFailure: 'skipped_failure' as StateEnum,
        Timeout: 'timeout' as StateEnum
    };
    export type StatusEnum = 'idle' | 'ok' | 'waiting_response' | 'temp_failure' | 'permanent_failure';
    export const StatusEnum = {
        Idle: 'idle' as StatusEnum,
        Ok: 'ok' as StatusEnum,
        WaitingResponse: 'waiting_response' as StatusEnum,
        TempFailure: 'temp_failure' as StatusEnum,
        PermanentFailure: 'permanent_failure' as StatusEnum
    };
}


