/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminInventoryItem } from './admin-inventory-item';


/**
 * An association between a product variant and an inventory item.
 */
export interface AdminProductVariantInventoryItemLink { 
    /**
     * The ID of the association.
     */
    id: string;
    /**
     * The associated product variant\'s ID.
     */
    variant_id: string;
    variant?: object;
    /**
     * The associated inventory item\'s ID.
     */
    inventory_item_id: string;
    inventory?: AdminInventoryItem;
}

