/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminNotification } from './admin-notification';


/**
 * The paginated list of notifications.
 */
export interface AdminNotificationListResponse { 
    /**
     * The maximum number of items returned.
     */
    limit: number;
    /**
     * The number of items skipped before retrieving the returned items.
     */
    offset: number;
    /**
     * The total count of items.
     */
    count: number;
    /**
     * The list of notifications.
     */
    notifications: Array<AdminNotification>;
}

