/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminCampaignBudget } from './admin-campaign-budget';


/**
 * The campaign\'s details.
 */
export interface AdminCampaign { 
    /**
     * The campaign\'s ID.
     */
    id: string;
    /**
     * The campaign\'s name.
     */
    name: string;
    /**
     * The campaign\'s description.
     */
    description: string;
    /**
     * The campaign\'s currency.
     */
    currency: string;
    /**
     * The campaign\'s identifier.
     */
    campaign_identifier: string;
    /**
     * The date and time that the campaign starts.
     */
    starts_at: string;
    /**
     * The date and time that the campaign ends.
     */
    ends_at: string;
    budget: AdminCampaignBudget;
    /**
     * The date the campaign was created.
     */
    created_at: string;
    /**
     * The date the campaign was updated.
     */
    updated_at: string;
    /**
     * The date the campaign was deleted.
     */
    deleted_at: string;
}

