/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminOrderPreview } from './admin-order-preview';
import { AdminReturn } from './admin-return';


/**
 * The details of an exchange\'s return.
 */
export interface AdminExchangeReturnResponse { 
    order_preview: AdminOrderPreview;
    'return': AdminReturn;
}

