/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The details of the shipping profile\'s deletion.
 */
export interface AdminShippingProfileDeleteResponse { 
    /**
     * The shipping profile\'s ID.
     */
    id: string;
    /**
     * The name of the deleted object.
     */
    object: string;
    /**
     * Whether the shipping profile was deleted.
     */
    deleted: boolean;
}

