/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The refund reason\'s details.
 */
export interface AdminCreateRefundReason { 
    /**
     * The refund reason\'s label.
     */
    label: string;
    /**
     * The refund reason\'s description.
     */
    description?: string;
}

