/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A tax rate rule.
 */
export interface AdminUpdateTaxRateRulesInner { 
    /**
     * The name of the table this rule references.
     */
    reference: string;
    /**
     * The ID of the record in the table that the rule references.
     */
    reference_id: string;
}

