/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The fulfillment option\'s details.
 */
export interface AdminFulfillmentProviderOption { 
    /**
     * The fulfillment option\'s ID.
     */
    id: string;
    /**
     * Whether the fulfillment option is used for returns.
     */
    is_return: boolean;
}

