/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The details of canceling a return.
 */
export interface AdminPostCancelReturnReqSchema { 
    /**
     * Whether to send the customer a notification about the return\'s cancelation.
     */
    no_notification?: boolean;
}

