/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The properties to update in a user.
 */
export interface AdminUpdateUser { 
    /**
     * The user\'s first name.
     */
    first_name?: string;
    /**
     * The user\'s last name.
     */
    last_name?: string;
    /**
     * The URL of the user\'s avatar.
     */
    avatar_url?: string;
    /**
     * The user\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
}

