/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminApiKey } from './admin-api-key';


/**
 * The API key\'s details.
 */
export interface AdminApiKeyResponse { 
    api_key: AdminApiKey;
}

