/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminCreatePromotionRuleValues } from './admin-create-promotion-rule-values';


/**
 * The properties to update in a buy rule.
 */
export interface AdminUpdatePromotionRule { 
    /**
     * The buy rule\'s ID.
     */
    id: string;
    /**
     * The operator used to check whether the buy rule applies on a cart. For example, `eq` means that the cart\'s value for the specified attribute must match the specified value.
     */
    operator?: AdminUpdatePromotionRule.OperatorEnum;
    /**
     * The buy rule\'s description.
     */
    description?: string;
    /**
     * The attribute to compare against when checking whether a promotion can be applied on a cart.
     */
    attribute?: string;
    values: AdminCreatePromotionRuleValues;
}
export namespace AdminUpdatePromotionRule {
    export type OperatorEnum = 'gte' | 'lte' | 'gt' | 'lt' | 'eq' | 'ne' | 'in';
    export const OperatorEnum = {
        Gte: 'gte' as OperatorEnum,
        Lte: 'lte' as OperatorEnum,
        Gt: 'gt' as OperatorEnum,
        Lt: 'lt' as OperatorEnum,
        Eq: 'eq' as OperatorEnum,
        Ne: 'ne' as OperatorEnum,
        In: 'in' as OperatorEnum
    };
}


