/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminCustomerGroup } from './admin-customer-group';


/**
 * The customer group\'s details.
 */
export interface AdminCustomerGroupResponse { 
    customer_group: AdminCustomerGroup;
}

