/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The customer group\'s details.
 */
export interface AdminCustomerGroup { 
    /**
     * The customer group\'s ID.
     */
    id: string;
    /**
     * The customer group\'s name.
     */
    name: string;
    /**
     * The customer group\'s customers.
     */
    customers: Array<object>;
    /**
     * The customer group\'s metadata, used to store custom key-value pairs.
     */
    metadata: object;
    /**
     * The customer group\'s creation date.
     */
    created_at: string;
    /**
     * The customer group\'s update date.
     */
    updated_at: string;
}

