/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The details to update in an API key.
 */
export interface AdminUpdateApiKey { 
    /**
     * The API key\'s title.
     */
    title: string;
}

