/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An item\'s details.
 */
export interface AdminPostReturnsRequestItemsReqSchemaItemsInner { 
    /**
     * The item\'s ID.
     */
    id: string;
    /**
     * The item\'s quantity.
     */
    quantity: number;
    /**
     * The item\'s description.
     */
    description?: string;
    /**
     * A note viewed only by admin users.
     */
    internal_note?: string;
    /**
     * The ID of the associated return reason.
     */
    reason_id?: string;
    /**
     * The item\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
}

