/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The price preference\'s details.
 */
export interface AdminCreatePricePreference { 
    /**
     * The name of the attribute the price preference applies on.
     */
    attribute?: string;
    /**
     * The attribute\'s value.
     */
    value?: string;
    /**
     * Whether the price is tax inclusive if the value of the specified attribute matches the specified value.
     */
    is_tax_inclusive?: boolean;
}

