/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminInvite } from './admin-invite';


/**
 * The invite\'s details.
 */
export interface AdminInviteResponse { 
    invite: AdminInvite;
}

