/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The tax rate rule\'s details.
 */
export interface AdminCreateTaxRateRule { 
    /**
     * The name of a table in the database that this rule points to.
     */
    reference: string;
    /**
     * The ID of a record in the table specified in reference.
     */
    reference_id: string;
}

