/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The details of canceling an exchange.
 */
export interface AdminPostCancelExchangeReqSchema { 
    /**
     * Whether to send a notification to the customer about the exchange\'s cancelation.
     */
    no_notification?: boolean;
}

