/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The return receival details.
 */
export interface AdminPostReceiveReturnsReqSchema { 
    /**
     * A note viewed only by admin users.
     */
    internal_note?: string;
    /**
     * The return\'s description.
     */
    description?: string;
    /**
     * The return\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
}

