/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminBatchProductVariantResponseDeleted } from './admin-batch-product-variant-response-deleted';
import { AdminProductVariant } from './admin-product-variant';


/**
 * The details of the product variants created, updated, or deleted.
 */
export interface AdminBatchProductVariantResponse { 
    /**
     * The created product variants.
     */
    created: Array<AdminProductVariant>;
    /**
     * The updated product variants.
     */
    updated: Array<AdminProductVariant>;
    deleted: AdminBatchProductVariantResponseDeleted;
}

