/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The order edit\'s details.
 */
export interface AdminPostOrderEditsReqSchema { 
    /**
     * The ID of the order this edit is for.
     */
    order_id: string;
    /**
     * The order edit\'s description.
     */
    description?: string;
    /**
     * A note viewed only by admin users.
     */
    internal_note?: string;
    /**
     * The order edit\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
}

