/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A price\'s details.
 */
export interface AdminCreatePriceListPricesInner { 
    /**
     * The price\'s currency code.
     */
    currency_code: string;
    /**
     * The price\'s amount.
     */
    amount: number;
    /**
     * The ID of the product variant this price is for.
     */
    variant_id: string;
    /**
     * The minimum quantity required in the cart for this price to be applied.
     */
    min_quantity?: number;
    /**
     * The maximum quantity in the cart that shouldn\'t be crossed for this price to be applied.
     */
    max_quantity?: number;
    /**
     * The price\'s rules.
     */
    rules?: object;
}

