/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The confirmation\'s details.
 */
export interface AdminPostReturnsConfirmRequestReqSchema { 
    /**
     * Whether to send the customer a notification about the confirmation.
     */
    no_notification?: boolean;
}

