/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The product option\'s details.
 */
export interface AdminCreateProductOption { 
    /**
     * The product option\'s title.
     */
    title: string;
    /**
     * The product option\'s values.
     */
    values: Array<string>;
}

