/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminOrderPreview } from './admin-order-preview';


/**
 * The preview of an order.
 */
export interface AdminOrderPreviewResponse { 
    order: AdminOrderPreview;
}

