/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The tax rate rule\'s details.
 */
export interface AdminTaxRateRule { 
    /**
     * The name of the table this rule references.
     */
    reference: string;
    /**
     * The ID of a record in the table that this rule references.
     */
    reference_id: string;
}

