/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The inventory level\'s details.
 */
export interface AdminBatchInventoryItemLocationsLevelUpdateInner { 
    /**
     * The inventory level\'s stocked quantity.
     */
    stocked_quantity?: number;
    /**
     * The inventory level\'s incoming quantity.
     */
    incoming_quantity?: number;
    /**
     * The associated stock location\'s ID.
     */
    location_id: string;
    /**
     * The ID of the location level.
     */
    id?: string;
}

