/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The sales channel\'s details.
 */
export interface AdminBatchUpdateProductSalesChannelsInner { 
    /**
     * The sales channel\'s ID.
     */
    id: string;
}

