/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminCustomerAddress } from './admin-customer-address';


/**
 * The address\'s details.
 */
export interface AdminCustomerAddressResponse { 
    address: AdminCustomerAddress;
}

