/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminCurrency } from './admin-currency';


/**
 * The details of a store\'s currency.
 */
export interface AdminStoreCurrency { 
    /**
     * The currency\'s ID.
     */
    id: string;
    /**
     * The currency\'s code.
     */
    currency_code: string;
    /**
     * The ID of the store this currency belongs to.
     */
    store_id: string;
    /**
     * Whether this currency is the default in the store.
     */
    is_default: boolean;
    currency: AdminCurrency;
    /**
     * The date the currency was created.
     */
    created_at: string;
    /**
     * The date the currency was updated.
     */
    updated_at: string;
    /**
     * The date the currency was deleted.
     */
    deleted_at: string;
}

