/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminOrderLineItem } from './admin-order-line-item';
import { AdminOrderItemHistory } from './admin-order-item-history';


/**
 * The order item\'s details.
 */
export interface AdminOrderItem { 
    /**
     * The ID of the order this item belongs to.
     */
    order_id: string;
    /**
     * The ID of the associated line item.
     */
    item_id: string;
    /**
     * The order item\'s version.
     */
    version: number;
    history: AdminOrderItemHistory;
    item: AdminOrderLineItem;
}

