/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminSalesChannel } from './admin-sales-channel';
import { AdminStockLocationAddress } from './admin-stock-location-address';
import { AdminFulfillmentProvider } from './admin-fulfillment-provider';


/**
 * The stock location\'s details.
 */
export interface AdminStockLocation { 
    /**
     * The location\'s ID.
     */
    id: string;
    /**
     * The location\'s name.
     */
    name: string;
    /**
     * The ID of the associated address.
     */
    address_id: string;
    address?: AdminStockLocationAddress;
    /**
     * The sales channels associated with the location.
     */
    sales_channels?: Array<AdminSalesChannel>;
    /**
     * The fulfillment providers associated with the location.
     */
    fulfillment_providers?: Array<AdminFulfillmentProvider>;
    /**
     * The fulfillment sets associated with the location.
     */
    fulfillment_sets?: Array<object>;
}

