/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminPostClaimsAddItemsReqSchemaItemsInner } from './admin-post-claims-add-items-req-schema-items-inner';


/**
 * The details of the outbound items to add to the claim.
 */
export interface AdminPostClaimsAddItemsReqSchema { 
    /**
     * The outbound item\'s details.
     */
    items?: Array<AdminPostClaimsAddItemsReqSchemaItemsInner>;
}

