/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An item\'s details.
 */
export interface AdminPostClaimsAddItemsReqSchemaItemsInner { 
    /**
     * The ID of the associated product variant.
     */
    variant_id: string;
    /**
     * The quantity to send to the customer.
     */
    quantity: number;
    /**
     * The item\'s unit price.
     */
    unit_price?: number;
    /**
     * A note viewed only by admin users.
     */
    internal_note?: string;
    /**
     * The item\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
}

