/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The tax region\'s default tax rate.
 */
export interface AdminCreateTaxRegionDefaultTaxRate { 
    /**
     * The rate to charge.
     */
    rate?: number;
    /**
     * The code the tax rate is identified by
     */
    code: string;
    /**
     * The default tax rate\'s name.
     */
    name: string;
    /**
     * Whether the tax rate should be combined with parent rates.
     */
    is_combinable?: boolean;
    /**
     * The default tax rate\'s metadata, used to store custom key-value pairs.
     */
    metadata?: object;
}

