/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminFile } from './admin-file';


/**
 * A file\'s details.
 */
export interface AdminFileResponse { 
    file: AdminFile;
}

