/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The deleted products\' details.
 */
export interface AdminBatchProductResponseDeleted { 
    /**
     * The IDs of deleted products.
     */
    ids: Array<string>;
    /**
     * The name of the deleted objects.
     */
    object: string;
    /**
     * Whether the products were deleted.
     */
    deleted: boolean;
}

