/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminCollection } from './admin-collection';


/**
 * The collection\'s details.
 */
export interface AdminCollectionResponse { 
    collection: AdminCollection;
}

