/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The details of changing a workflow execution\'s step status.
 */
export interface AdminCreateWorkflowsAsyncResponse { 
    /**
     * The workflows execution\'s transaction ID.
     */
    transaction_id: string;
    /**
     * The ID of the step whose status was changed.
     */
    step_id: string;
    /**
     * Sets the step\'s response. It accepts any type.
     */
    response?: any | null;
    /**
     * Sets the compensation function\'s input. It accepts any response.
     */
    compensate_input?: any | null;
    /**
     * Whether to invoke or compensate the step.
     */
    action?: AdminCreateWorkflowsAsyncResponse.ActionEnum;
}
export namespace AdminCreateWorkflowsAsyncResponse {
    export type ActionEnum = 'invoke' | 'compensate';
    export const ActionEnum = {
        Invoke: 'invoke' as ActionEnum,
        Compensate: 'compensate' as ActionEnum
    };
}


