/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminReturnItem } from './admin-return-item';


/**
 * The return\'s details.
 */
export interface AdminReturn { 
    /**
     * The return\'s ID.
     */
    id: string;
    /**
     * The return\'s status.
     */
    status?: AdminReturn.StatusEnum;
    /**
     * The amount refunded by this return.
     */
    refund_amount?: number;
    /**
     * The ID of the associated order.
     */
    order_id: string;
    /**
     * The return\'s items.
     */
    items: Array<AdminReturnItem>;
    /**
     * The date the return was created.
     */
    created_at: string;
    /**
     * The date the return was canceled.
     */
    canceled_at: string;
    /**
     * The return\'s exchange id.
     */
    exchange_id?: string;
    /**
     * The return\'s location id.
     */
    location_id?: string;
    /**
     * The return\'s claim id.
     */
    claim_id?: string;
    /**
     * The return\'s order version.
     */
    order_version: number;
    /**
     * The return\'s display id.
     */
    display_id: number;
    /**
     * Whether the customer should receive notifications about the return\'s updates.
     */
    no_notification?: boolean;
    /**
     * The date the return was received.
     */
    received_at: string;
}
export namespace AdminReturn {
    export type StatusEnum = 'canceled' | 'requested' | 'received' | 'partially_received';
    export const StatusEnum = {
        Canceled: 'canceled' as StatusEnum,
        Requested: 'requested' as StatusEnum,
        Received: 'received' as StatusEnum,
        PartiallyReceived: 'partially_received' as StatusEnum
    };
}


