/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminCustomerGroup } from './admin-customer-group';
import { AdminCustomerAddress } from './admin-customer-address';


/**
 * The customer\'s details.
 */
export interface AdminCustomer { 
    /**
     * The customer\'s ID.
     */
    id: string;
    /**
     * Whether the customer is registered.
     */
    has_account: boolean;
    /**
     * The customer\'s groups.
     */
    groups?: Array<AdminCustomerGroup>;
    /**
     * The customer\'s email.
     */
    email: string;
    /**
     * The ID of the address used as the default billing address.
     */
    default_billing_address_id: string;
    /**
     * The ID of the address used as the default shipping address.
     */
    default_shipping_address_id: string;
    /**
     * The customer\'s company name.
     */
    company_name: string;
    /**
     * The customer\'s first name.
     */
    first_name: string;
    /**
     * The customer\'s last name.
     */
    last_name: string;
    /**
     * The customer\'s addresses.
     */
    addresses: Array<AdminCustomerAddress>;
    /**
     * The customer\'s phone.
     */
    phone?: string;
    /**
     * The customer\'s metadata, used to store custom key-value pairs.
     */
    metadata?: object;
    /**
     * The ID of the user that created this customer, if available.
     */
    created_by?: string;
    /**
     * The customer\'s creation date.
     */
    created_at?: string;
    /**
     * The customer\'s update date.
     */
    updated_at?: string;
    /**
     * The customer\'s deletion date.
     */
    deleted_at?: string;
}

