/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The version changes of the item.
 */
export interface AdminOrderItemHistoryVersion { 
    /**
     * The original version.
     */
    from: number;
    /**
     * The new version.
     */
    to: number;
}

