/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminWorkflowExecutionExecutionStepsValueInvoke } from './admin-workflow-execution-execution-steps-value-invoke';
import { AdminWorkflowExecutionExecutionStepsValueDefinition } from './admin-workflow-execution-execution-steps-value-definition';
import { AdminWorkflowExecutionExecutionStepsValueCompensate } from './admin-workflow-execution-execution-steps-value-compensate';


export interface AdminWorkflowExecutionExecutionStepsValue { 
    /**
     * The step\'s ID.
     */
    id?: string;
    invoke?: AdminWorkflowExecutionExecutionStepsValueInvoke;
    definition?: AdminWorkflowExecutionExecutionStepsValueDefinition;
    compensate?: AdminWorkflowExecutionExecutionStepsValueCompensate;
    /**
     * The step\'s depth in the workflow\'s execution.
     */
    depth?: number;
    /**
     * The timestamp the step started executing.
     */
    startedAt?: number;
}

