/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The return\'s details.
 */
export interface AdminPostReturnsReqSchema { 
    /**
     * The ID of the order the return belongs to.
     */
    order_id: string;
    /**
     * The ID of the location the items are returned to.
     */
    location_id?: string;
    /**
     * The return\'s description.
     */
    description?: string;
    /**
     * A note viewed only by admin users.
     */
    internal_note?: string;
    /**
     * Whether to send the customer a notification about the created return.
     */
    no_notification?: boolean;
    /**
     * The return\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
}

