/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The price\'s details.
 */
export interface AdminCreateShippingOptionPricesInnerOneOf { 
    /**
     * The price\'s currency code.
     */
    currency_code: string;
    /**
     * The price\'s amount.
     */
    amount: number;
}

