/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminWorkflowExecutionExecutionStepsValue } from './admin-workflow-execution-execution-steps-value';


/**
 * The workflow execution\'s steps details.
 */
export interface AdminWorkflowExecutionExecution { 
    /**
     * The execution\'s steps. Each object key is a step ID, and the value is the object whose properties are shown below.
     */
    steps: { [key: string]: AdminWorkflowExecutionExecutionStepsValue; };
}

