/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The details to update in an outbound item.
 */
export interface AdminPostExchangesItemsActionReqSchema { 
    /**
     * The item\'s quantity.
     */
    quantity?: number;
    /**
     * A note only viewed by admin users.
     */
    internal_note?: string;
}

