/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminCurrency } from './admin-currency';


/**
 * The currency\'s details.
 */
export interface AdminCurrencyResponse { 
    currency: AdminCurrency;
}

