/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The shipping option rule\'s details.
 */
export interface AdminShippingOptionRule { 
    /**
     * The shipping option rule\'s ID.
     */
    id: string;
    /**
     * The shipping option rule\'s attribute.
     */
    attribute: string;
    /**
     * The rule\'s operator.
     */
    operator: AdminShippingOptionRule.OperatorEnum;
    value: string;
    /**
     * The ID of the shipping option this rule is for.
     */
    shipping_option_id: string;
    /**
     * The date the shipping option rule was created.
     */
    created_at: string;
    /**
     * The date the shipping option rule was updated.
     */
    updated_at: string;
    /**
     * The date the shipping option rule was deleted.
     */
    deleted_at: string;
}
export namespace AdminShippingOptionRule {
    export type OperatorEnum = 'gt' | 'lt' | 'eq' | 'ne' | 'in' | 'lte' | 'gte' | 'nin';
    export const OperatorEnum = {
        Gt: 'gt' as OperatorEnum,
        Lt: 'lt' as OperatorEnum,
        Eq: 'eq' as OperatorEnum,
        Ne: 'ne' as OperatorEnum,
        In: 'in' as OperatorEnum,
        Lte: 'lte' as OperatorEnum,
        Gte: 'gte' as OperatorEnum,
        Nin: 'nin' as OperatorEnum
    };
}


