/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminCustomerInGroupFiltersDefaultShippingAddressId } from './admin-customer-in-group-filters-default-shipping-address-id';
import { AdminCustomerInGroupFiltersId } from './admin-customer-in-group-filters-id';
import { AdminCustomerInGroupFiltersDeletedAt } from './admin-customer-in-group-filters-deleted-at';
import { AdminCustomerInGroupFiltersCreatedBy } from './admin-customer-in-group-filters-created-by';
import { AdminCustomerInGroupFiltersEmail } from './admin-customer-in-group-filters-email';
import { AdminCustomerInGroupFiltersLastName } from './admin-customer-in-group-filters-last-name';
import { AdminCustomerInGroupFiltersFirstName } from './admin-customer-in-group-filters-first-name';
import { AdminCustomerInGroupFiltersCreatedAt } from './admin-customer-in-group-filters-created-at';
import { AdminCustomerInGroupFiltersUpdatedAt } from './admin-customer-in-group-filters-updated-at';
import { AdminCustomerInGroupFiltersCompanyName } from './admin-customer-in-group-filters-company-name';
import { AdminCustomerInGroupFiltersDefaultBillingAddressId } from './admin-customer-in-group-filters-default-billing-address-id';


/**
 * Filters to apply on customers to retrieve their groups.
 */
export interface AdminCustomerInGroupFilters { 
    id?: AdminCustomerInGroupFiltersId;
    email?: AdminCustomerInGroupFiltersEmail;
    default_billing_address_id?: AdminCustomerInGroupFiltersDefaultBillingAddressId;
    default_shipping_address_id?: AdminCustomerInGroupFiltersDefaultShippingAddressId;
    company_name?: AdminCustomerInGroupFiltersCompanyName;
    first_name?: AdminCustomerInGroupFiltersFirstName;
    last_name?: AdminCustomerInGroupFiltersLastName;
    created_by?: AdminCustomerInGroupFiltersCreatedBy;
    created_at?: AdminCustomerInGroupFiltersCreatedAt;
    updated_at?: AdminCustomerInGroupFiltersUpdatedAt;
    deleted_at?: AdminCustomerInGroupFiltersDeletedAt;
}

