/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminImportProductResponseSummary } from './admin-import-product-response-summary';


/**
 * The import process\'s details.
 */
export interface AdminImportProductResponse { 
    /**
     * The ID of the workflow execution\'s transaction. This is useful to confirm the import using the `/admin/products/:transaction-id/import` API route.
     */
    transaction_id: string;
    summary: AdminImportProductResponseSummary;
}

