/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminPostExchangesAddItemsReqSchemaItemsInner } from './admin-post-exchanges-add-items-req-schema-items-inner';


/**
 * The details of outbound items.
 */
export interface AdminPostExchangesAddItemsReqSchema { 
    /**
     * The details of outbound items.
     */
    items?: Array<AdminPostExchangesAddItemsReqSchemaItemsInner>;
}

