/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * the product collection\'s details.
 */
export interface AdminCreateCollection { 
    /**
     * The collection\'s title.
     */
    title: string;
    /**
     * The collection\'s handle.
     */
    handle?: string;
    /**
     * The collection\'s metadata, used to store custom key-value pairs.
     */
    metadata?: object;
}

