/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminUpdateStockLocationAddress } from './admin-update-stock-location-address';


/**
 * The properties to update in a stock location.
 */
export interface AdminUpdateStockLocation { 
    /**
     * The stock location\'s name.
     */
    name?: string;
    address?: AdminUpdateStockLocationAddress;
    /**
     * The ID of an existing stock location address to associate the stock location with.
     */
    address_id?: string;
    /**
     * The stock location\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
}

