/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminUpdateTaxRateRulesInner } from './admin-update-tax-rate-rules-inner';


/**
 * The properties to update in the tax rate.
 */
export interface AdminUpdateTaxRate { 
    /**
     * The rate to charge.
     */
    rate?: number;
    /**
     * The code that the tax rate is identified by.
     */
    code?: string;
    /**
     * The tax rate\'s rules.
     */
    rules?: Array<AdminUpdateTaxRateRulesInner>;
    /**
     * The tax rate\'s name.
     */
    name?: string;
    /**
     * Whether the tax rate is the default in the store.
     */
    is_default?: boolean;
    /**
     * Whether the tax rate should be combined with parent rates.
     */
    is_combinable?: boolean;
    /**
     * The tax rate\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
}

