/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The customer group\'s details.
 */
export interface AdminCreateCustomerGroup { 
    /**
     * The customer group\'s name.
     */
    name: string;
    /**
     * The customer group\'s metadata, used to store custom key-value pairs.
     */
    metadata?: object;
}

