/**
 * Medusa Storefront API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The region\'s details.
 */
export interface AdminCreateRegion {
    /**
     * The region\'s name.
     */
    name: string;
    /**
     * The region\'s currency code.
     */
    currency_code: string;
    /**
     * The region\'s countries.
     */
    countries?: Array<string>;
    /**
     * Whether taxes are calculated automatically during checkout-page in this region.
     */
    automatic_taxes?: boolean;
    /**
     * Whether prices in this region are tax inclusive.
     */
    is_tax_inclusive?: boolean;
    /**
     * The payment providers enabled in this region.
     */
    payment_providers?: Array<string>;
    /**
     * The region\'s metadata, used to store custom key-value pairs.
     */
    metadata?: object;
}

