/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminProductVariantInventoryBatchResponseCreatedOneOfInnerProductService } from './admin-product-variant-inventory-batch-response-created-one-of-inner-product-service';
import { AdminProductVariantInventoryBatchResponseCreatedOneOfInner } from './admin-product-variant-inventory-batch-response-created-one-of-inner';
import { AdminProductVariantInventoryLink } from './admin-product-variant-inventory-link';
import { AdminProductVariantInventoryBatchResponseCreatedOneOfInnerInventoryService } from './admin-product-variant-inventory-batch-response-created-one-of-inner-inventory-service';


/**
 * @type AdminProductVariantInventoryBatchResponseCreated
 * @export
 */
export type AdminProductVariantInventoryBatchResponseCreated = AdminProductVariantInventoryLink | Array<AdminProductVariantInventoryBatchResponseCreatedOneOfInner>;

