/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminProduct } from './admin-product';


/**
 * The details of the product option deletion.
 */
export interface AdminProductOptionDeleteResponse { 
    /**
     * The product option\'s ID.
     */
    id: string;
    /**
     * The name of the deleted object.
     */
    object: string;
    /**
     * Whether the product option was deleted.
     */
    deleted: boolean;
    parent?: AdminProduct;
}

