/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The product variant\'s details.
 */
export interface AdminProductVariantInventoryBatchResponseCreatedOneOfInnerProductService { 
    /**
     * The ID of the product variant.
     */
    variant_id: string;
}

