/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A store currency.
 */
export interface AdminUpdateStoreSupportedCurrenciesInner { 
    /**
     * The currency\'s code.
     */
    currency_code: string;
    /**
     * Whether the currency is the default in the store.
     */
    is_default?: boolean;
    /**
     * Whether prices using this currency are tax inclusive.
     */
    is_tax_inclusive?: boolean;
}

