/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The inventory item\'s details.
 */
export interface AdminCreateInventoryItem { 
    /**
     * The inventory item\'s SKU.
     */
    sku?: string;
    /**
     * The inventory item\'s HS code.
     */
    hs_code?: string;
    /**
     * The inventory item\'s weight.
     */
    weight?: number;
    /**
     * The inventory item\'s length.
     */
    length?: number;
    /**
     * The inventory item\'s height.
     */
    height?: number;
    /**
     * The inventory item\'s width.
     */
    width?: number;
    /**
     * The inventory item\'s origin country.
     */
    origin_country?: string;
    /**
     * The inventory item\'s mid code.
     */
    mid_code?: string;
    /**
     * The inventory item\'s material.
     */
    material?: string;
    /**
     * The inventory item\'s title.
     */
    title?: string;
    /**
     * The description of the variant associated with the inventory item.
     */
    description?: string;
    /**
     * Whether the item requires shipping.
     */
    requires_shipping?: boolean;
    /**
     * The inventory item\'s thumbnail.
     */
    thumbnail?: string;
    /**
     * The inventory item\'s metadata, used to store custom key-value pairs.
     */
    metadata?: object;
}

