/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The exchange\'s details.
 */
export interface AdminPostOrderExchangesReqSchema { 
    /**
     * The ID of the order this exchange is created for.
     */
    order_id: string;
    /**
     * The exchange\'s description.
     */
    description?: string;
    /**
     * A note viewed only by admin users.
     */
    internal_note?: string;
    /**
     * The exchange\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
}

