/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The shipping method\'s details.
 */
export interface AdminPostOrderEditsShippingActionReqSchema { 
    /**
     * Set a custom price for the shipping method.
     */
    custom_amount?: number;
    /**
     * A note viewed only by admin users.
     */
    internal_note?: string;
    /**
     * The order edit\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
}

