/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The details to update in a product option.
 */
export interface AdminUpdateProductOption { 
    /**
     * The option\'s title.
     */
    title?: string;
    /**
     * The option\'s values.
     */
    values?: Array<string>;
}

