/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The outbound shipping method\'s details.
 */
export interface AdminPostExchangesShippingReqSchema { 
    /**
     * The ID of the associated shipping option.
     */
    shipping_option_id: string;
    /**
     * Set a custom amount for the shipping method.
     */
    custom_amount?: number;
    /**
     * The shipping method\'s description.
     */
    description?: string;
    /**
     * A note viewed by admin users only.
     */
    internal_note?: string;
    /**
     * The exchange\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
}

