/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminProductVariantInventoryBatchResponseCreated } from './admin-product-variant-inventory-batch-response-created';
import { AdminProductVariantInventoryBatchResponseDeleted } from './admin-product-variant-inventory-batch-response-deleted';
import { AdminProductVariantInventoryBatchResponseUpdated } from './admin-product-variant-inventory-batch-response-updated';


/**
 * The created, updated, and deleted associations between variants and inventory items.
 */
export interface AdminProductVariantInventoryBatchResponse { 
    created: AdminProductVariantInventoryBatchResponseCreated;
    updated: AdminProductVariantInventoryBatchResponseUpdated;
    deleted: AdminProductVariantInventoryBatchResponseDeleted;
}

