/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminOrderPreview } from './admin-order-preview';
import { AdminExchange } from './admin-exchange';


/**
 * A preview of the order once the exchange is applied.
 */
export interface AdminExchangePreviewResponse { 
    order_preview: AdminOrderPreview;
    exchange: AdminExchange;
}

