/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminCustomerInGroupFiltersEmailOneOfEq } from './admin-customer-in-group-filters-email-one-of-eq';
import { AdminCustomerInGroupFiltersEmailOneOf } from './admin-customer-in-group-filters-email-one-of';
import { AdminCustomerInGroupFiltersEmailOneOfNot } from './admin-customer-in-group-filters-email-one-of-not';


/**
 * @type AdminCustomerInGroupFiltersEmail
 * @export
 */
export type AdminCustomerInGroupFiltersEmail = AdminCustomerInGroupFiltersEmailOneOf | Array<string> | string;

