/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminPaymentSession } from './admin-payment-session';
import { AdminPayment } from './admin-payment';
import { AdminPaymentProvider } from './admin-payment-provider';


/**
 * The payment collection\'s details.
 */
export interface AdminPaymentCollection { 
    /**
     * The payment collection\'s ID.
     */
    id: string;
    /**
     * The payment collection\'s currency code.
     */
    currency_code: string;
    /**
     * The total amount to be paid.
     */
    amount: number;
    /**
     * The total authorized amount of the collection\'s payments.
     */
    authorized_amount?: number;
    /**
     * The total captured amount of the collection\'s payments.
     */
    captured_amount?: number;
    /**
     * The total refunded amount of the collection\'s payments.
     */
    refunded_amount?: number;
    /**
     * The date the payment collection was completed.
     */
    completed_at?: string;
    /**
     * The date the payment collection was created.
     */
    created_at?: string;
    /**
     * The date the payment collection was updated.
     */
    updated_at?: string;
    /**
     * The payment collection\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
    /**
     * The payment collection\'s status.
     */
    status: AdminPaymentCollection.StatusEnum;
    /**
     * The payment provider used to process the collection\'s payments and sessions.
     */
    payment_providers: Array<AdminPaymentProvider>;
    /**
     * The payment collection\'s payment sessions.
     */
    payment_sessions?: Array<AdminPaymentSession>;
    /**
     * The payment collection\'s payments.
     */
    payments?: Array<AdminPayment>;
}
export namespace AdminPaymentCollection {
    export type StatusEnum = 'canceled' | 'not_paid' | 'awaiting' | 'authorized' | 'partially_authorized';
    export const StatusEnum = {
        Canceled: 'canceled' as StatusEnum,
        NotPaid: 'not_paid' as StatusEnum,
        Awaiting: 'awaiting' as StatusEnum,
        Authorized: 'authorized' as StatusEnum,
        PartiallyAuthorized: 'partially_authorized' as StatusEnum
    };
}


