/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The geo zone\'s geo zones.
 */
export interface AdminGeoZone { 
    /**
     * The geo zone\'s ID.
     */
    id: string;
    /**
     * The geo zone\'s type.
     */
    type: AdminGeoZone.TypeEnum;
    /**
     * The geo zone\'s country code.
     */
    country_code: string;
    /**
     * The geo zone\'s province code.
     */
    province_code: string;
    /**
     * The geo zone\'s city.
     */
    city: string;
    /**
     * The geo zone\'s postal expression.
     */
    postal_expression: object;
    /**
     * The geo zone\'s created at.
     */
    created_at: string;
    /**
     * The geo zone\'s updated at.
     */
    updated_at: string;
    /**
     * The geo zone\'s deleted at.
     */
    deleted_at: string;
}
export namespace AdminGeoZone {
    export type TypeEnum = 'country' | 'province' | 'city' | 'zip';
    export const TypeEnum = {
        Country: 'country' as TypeEnum,
        Province: 'province' as TypeEnum,
        City: 'city' as TypeEnum,
        Zip: 'zip' as TypeEnum
    };
}


