/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The products removal details.
 */
export interface AdminLinkPriceListProducts { 
    /**
     * The products to remove from the price list.
     */
    remove?: Array<string>;
}

