/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminPayment } from './admin-payment';


/**
 * The payment\'s details.
 */
export interface AdminPaymentResponse { 
    payment: AdminPayment;
}

