/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The shipping profile\'s details.
 */
export interface AdminCreateShippingProfile { 
    /**
     * The shipping profile\'s name.
     */
    name: string;
    /**
     * The shipping profile\'s type.
     */
    type: string;
    /**
     * The shipping profile\'s metadata, used to store custom key-value pairs.
     */
    metadata?: object;
}

