/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BaseOrderLineItemTaxLine } from './base-order-line-item-tax-line';
import { BaseOrderLineItemAdjustment } from './base-order-line-item-adjustment';
import { AdminProductVariant } from './admin-product-variant';
import { AdminProduct } from './admin-product';


/**
 * The item\'s details.
 */
export interface AdminOrderLineItem { 
    /**
     * The item\'s ID.
     */
    id: string;
    /**
     * The item\'s title.
     */
    title: string;
    /**
     * The item\'s subtitle.
     */
    subtitle: string;
    /**
     * The URL of the item\'s thumbnail.
     */
    thumbnail: string;
    variant?: AdminProductVariant;
    /**
     * The ID of the associated variant.
     */
    variant_id: string;
    product?: AdminProduct;
    /**
     * The ID of the associated product.
     */
    product_id: string;
    /**
     * The item\'s product title.
     */
    product_title: string;
    /**
     * The item\'s product description.
     */
    product_description: string;
    /**
     * The item\'s product subtitle.
     */
    product_subtitle: string;
    /**
     * The item\'s product type.
     */
    product_type: string;
    /**
     * The ID of the collection the item\'s product belongs to.
     */
    product_collection: string;
    /**
     * The item\'s product handle.
     */
    product_handle: string;
    /**
     * The item\'s variant SKU.
     */
    variant_sku: string;
    /**
     * The item\'s variant barcode.
     */
    variant_barcode: string;
    /**
     * The item\'s variant title.
     */
    variant_title: string;
    /**
     * The values of the item variant\'s options.
     */
    variant_option_values: object;
    /**
     * Whether the item requires shipping.
     */
    requires_shipping: boolean;
    /**
     * Whether the item is discountable.
     */
    is_discountable: boolean;
    /**
     * Whether the item is tax inclusive.
     */
    is_tax_inclusive: boolean;
    /**
     * The original price of the item before a promotion or sale.
     */
    compare_at_unit_price?: number;
    /**
     * The item\'s unit price.
     */
    unit_price: number;
    /**
     * The item\'s quantity.
     */
    quantity: number;
    /**
     * The item\'s tax lines.
     */
    tax_lines?: Array<BaseOrderLineItemTaxLine>;
    /**
     * The item\'s adjustments.
     */
    adjustments?: Array<BaseOrderLineItemAdjustment>;
    detail: object;
    /**
     * The date the item was created.
     */
    created_at: string;
    /**
     * The date the item was updated.
     */
    updated_at: string;
    /**
     * The item\'s metadata, can hold custom key-value pairs.
     */
    metadata: object;
    /**
     * The item\'s total including taxes, excluding promotions.
     */
    original_total: number;
    /**
     * The item\'s total excluding taxes, including promotions.
     */
    original_subtotal: number;
    /**
     * The total taxes of the item, excluding promotions.
     */
    original_tax_total: number;
    /**
     * The total taxes of the item, including promotions.
     */
    item_total: number;
    /**
     * The item\'s total excluding taxes, including promotions.
     */
    item_subtotal: number;
    /**
     * The total taxes of the item, including promotions.
     */
    item_tax_total: number;
    /**
     * The item\'s total, including taxes and promotions.
     */
    total: number;
    /**
     * The item\'s subtotal excluding taxes, including promotions.
     */
    subtotal: number;
    /**
     * The tax total of the item including promotions.
     */
    tax_total: number;
    /**
     * The total discount amount of the item.
     */
    discount_total: number;
    /**
     * The total taxes applied on the discounted amount.
     */
    discount_tax_total: number;
    /**
     * The total refundable amount of the item\'s total.
     */
    refundable_total: number;
    /**
     * The total refundable amount of the item\'s total for a single quantity.
     */
    refundable_total_per_unit: number;
    /**
     * The ID of the associated product\'s type.
     */
    product_type_id: string;
}

