/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The price\'s rules.
 */
export interface AdminCreateProductVariantPriceRules { 
    /**
     * The ID of a region.
     */
    region_id: string;
}

