/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The details of the product type to create.
 */
export interface AdminCreateProductType { 
    /**
     * The product\'s metadata, used to store custom key-value pairs.
     */
    metadata?: object;
    /**
     * The product type\'s value.
     */
    value: string;
}

