/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The notification\'s details.
 */
export interface AdminNotification { 
    /**
     * The notification\'s ID.
     */
    id: string;
    /**
     * Where to send the notification to. For example, if `channel` is `email`, this can be an email number.
     */
    to: string;
    /**
     * Through which channel is the notification sent through.
     */
    channel: string;
    /**
     * The ID of the template in a third-party service used as the notification\'s shape.
     */
    template: string;
    /**
     * Data payload to send with the notification.
     */
    data?: object;
    /**
     * What triggered this notification.
     */
    trigger_type?: string;
    /**
     * The ID of the associated resource. For example, if the notification was triggered because an order was created, this would be the ID of the order.
     */
    resource_id?: string;
    /**
     * The type of the resource that triggered the notification.
     */
    resource_type?: string;
    /**
     * The ID of the user or customer that\'s receiving this notification.
     */
    receiver_id?: string;
    /**
     * The ID of the original notification, if this notification is resent.
     */
    original_notification_id?: string;
    /**
     * The ID of the notification in an external or third-party system.
     */
    external_id?: string;
    /**
     * The ID of the provider used to send the notification.
     */
    provider_id: string;
    /**
     * The date the notification was created.
     */
    created_at: string;
}

