/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminBatchUpdateInventoryItemsLocationLevels } from './admin-batch-update-inventory-items-location-levels';
import { AdminBatchCreateInventoryItemsLocationLevels } from './admin-batch-create-inventory-items-location-levels';


/**
 * The inventory levels to manage.
 */
export interface AdminBatchInventoryItemsLocationLevels { 
    /**
     * The inventory levels to create.
     */
    create: Array<AdminBatchCreateInventoryItemsLocationLevels>;
    /**
     * The inventory levels to update.
     */
    update: Array<AdminBatchUpdateInventoryItemsLocationLevels>;
    /**
     * The IDs of the inventory levels to delete.
     */
    'delete': Array<string>;
    /**
     * Whether to delete specified inventory levels even if they have a non-zero stocked quantity.
     */
    force?: boolean;
}

