/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A file\'s details.
 */
export interface AdminFile { 
    /**
     * The file\'s ID.
     */
    id: string;
    /**
     * The file\'s URL.
     */
    url: string;
}

