/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An item\'s details.
 */
export interface AdminPostReturnsReceiveItemsReqSchemaItemsInner { 
    /**
     * The ID of the item in the order.
     */
    id: string;
    /**
     * The item\'s quantity.
     */
    quantity: number;
    /**
     * The item\'s description.
     */
    description?: string;
    /**
     * A note viewed only by admin users.
     */
    internal_note?: string;
}

