/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BaseOrderTransaction } from './base-order-transaction';
import { AdminOrder } from './admin-order';
import { AdminOrderShippingMethod } from './admin-order-shipping-method';
import { AdminReturn } from './admin-return';
import { BaseClaimItem } from './base-claim-item';


/**
 * The claim\'s details.
 */
export interface AdminClaim { 
    /**
     * The claim\'s ID.
     */
    id: string;
    /**
     * The ID of the order associated with the claim.
     */
    order_id: string;
    /**
     * The order items targetted by the claim.
     */
    claim_items: Array<BaseClaimItem>;
    /**
     * The outbound or new items of the claim.
     */
    additional_items: Array<BaseClaimItem>;
    'return': AdminReturn;
    /**
     * The ID of the associated return.
     */
    return_id?: string;
    /**
     * Whether the customer should be notified about changes in the claim.
     */
    no_notification?: boolean;
    /**
     * The amount to be refunded.
     */
    refund_amount?: number;
    /**
     * The claim\'s display ID.
     */
    display_id: number;
    /**
     * The claim\'s shipping methods.
     */
    shipping_methods?: Array<AdminOrderShippingMethod>;
    /**
     * The claim\'s transactions.
     */
    transactions?: Array<BaseOrderTransaction>;
    /**
     * The claim\'s metadata, used to store custom key-value pairs.
     */
    metadata?: object;
    /**
     * The claim\'s creation date.
     */
    created_at: string;
    /**
     * The claim\'s update date.
     */
    updated_at: string;
    order: AdminOrder;
    /**
     * The claim\'s type.
     */
    type: AdminClaim.TypeEnum;
    /**
     * The version of the order when the claim is applied.
     */
    order_version: string;
    /**
     * The ID of the user that created the claim.
     */
    created_by?: string;
    /**
     * The date the claim was canceled.
     */
    canceled_at: string;
    /**
     * The date the claim was deleted.
     */
    deleted_at?: string;
}
export namespace AdminClaim {
    export type TypeEnum = 'replace' | 'refund';
    export const TypeEnum = {
        Replace: 'replace' as TypeEnum,
        Refund: 'refund' as TypeEnum
    };
}


