/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminStore } from './admin-store';


/**
 * The store\'s details.
 */
export interface AdminStoreResponse { 
    store: AdminStore;
}

