/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The product tag\'s details.
 */
export interface AdminCreateProductTag { 
    /**
     * The product tag\'s value.
     */
    value: string;
    /**
     * The product tag\'s metadata, used to store custom key-value pairs.
     */
    metadata?: object;
}

