/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The details to update in the item.
 */
export interface AdminPostClaimsItemsActionReqSchema { 
    /**
     * The item\'s quantity.
     */
    quantity?: number;
    /**
     * The ID of the return reason associated with the item.
     */
    reason_id?: string;
    /**
     * A note that\'s only viewed by admin users.
     */
    internal_note?: string;
}

