/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminCampaign } from './admin-campaign';


/**
 * The campaign\'s details.
 */
export interface AdminCampaignResponse { 
    campaign: AdminCampaign;
}

