/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminProductVariantInventoryItemLink } from './admin-product-variant-inventory-item-link';
import { AdminProductOptionValue } from './admin-product-option-value';
import { AdminPrice } from './admin-price';
import { BaseCalculatedPriceSet } from './base-calculated-price-set';


/**
 * The product variant\'s details.
 */
export interface AdminProductVariant { 
    /**
     * The variant\'s prices.
     */
    prices: Array<AdminPrice>;
    /**
     * The variant\'s ID.
     */
    id: string;
    /**
     * The variant\'s title.
     */
    title: string;
    /**
     * The variant\'s SKU.
     */
    sku: string;
    /**
     * The variant\'s barcode.
     */
    barcode: string;
    /**
     * The variant\'s EAN code.
     */
    ean: string;
    /**
     * The variant\'s UPC.
     */
    upc: string;
    /**
     * Whether the variant can be ordered even if it\'s out of stock.
     */
    allow_backorder: boolean;
    /**
     * Whether the Medusa application manages the variant\'s inventory quantity and availablility. If disabled, the variant is always considered in stock.
     */
    manage_inventory: boolean;
    /**
     * The variant\'s inventory quantity. This is only included if you pass in the `fields` query parameter a `+variants.inventory_quantity` parameter.
     */
    inventory_quantity?: number;
    /**
     * The variant\'s HS code.
     */
    hs_code: string;
    /**
     * The variant\'s origin country.
     */
    origin_country: string;
    /**
     * The variant\'s MID code.
     */
    mid_code: string;
    /**
     * The variant\'s material.
     */
    material: string;
    /**
     * The variant\'s weight.
     */
    weight: number;
    /**
     * The variant\'s length.
     */
    length: number;
    /**
     * The variant\'s height.
     */
    height: number;
    /**
     * The variant\'s width.
     */
    width: number;
    /**
     * The variant\'s rank among its sibling variants.
     */
    variant_rank?: number;
    /**
     * The variant\'s option values.
     */
    options: Array<AdminProductOptionValue>;
    product?: object;
    /**
     * The ID of the product that the variant belongs to.
     */
    product_id?: string;
    calculated_price?: BaseCalculatedPriceSet;
    /**
     * The date the variant was created.
     */
    created_at: string;
    /**
     * The date the variant was updated.
     */
    updated_at: string;
    /**
     * The date the variant was deleted.
     */
    deleted_at: string;
    /**
     * The variant\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
    /**
     * The variant\'s inventory items.
     */
    inventory_items?: Array<AdminProductVariantInventoryItemLink>;
}

