/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The import\'s details.
 */
export interface AdminImportProductRequest { 
    /**
     * A File to upload.
     */
    file: object;
}

