/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminOrderPreview } from './admin-order-preview';
import { AdminClaim } from './admin-claim';


/**
 * The details of the claim, as well as a preview of the order when the claim is applied.
 */
export interface AdminClaimPreviewResponse { 
    order_preview: AdminOrderPreview;
    claim: AdminClaim;
}

