/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The sales channel\'s details.
 */
export interface AdminSalesChannel { 
    /**
     * The sales channel\'s ID.
     */
    id: string;
    /**
     * The sales channel\'s name.
     */
    name: string;
    /**
     * The sales channel\'s description.
     */
    description: string;
    /**
     * Whether the sales channel is disabled.
     */
    is_disabled: boolean;
    /**
     * The sales channel\'s metadata, can hold custom key-value pairs.
     */
    metadata: object;
    /**
     * The date the sales channel was created.
     */
    created_at: string;
    /**
     * The date the sales channel was updated.
     */
    updated_at: string;
    /**
     * The date the sales channel was deleted.
     */
    deleted_at: string;
}

