/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The details of the return reason to create.
 */
export interface AdminCreateReturnReason { 
    /**
     * The return reason\'s value.
     */
    value: string;
    /**
     * The return reason\'s label.
     */
    label: string;
    /**
     * The return reason\'s description.
     */
    description?: string;
    /**
     * The ID of the parent return reason.
     */
    parent_return_reason_id?: string;
    /**
     * The return reason\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
}

