/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminPostReturnsReceiveItemsReqSchemaItemsInner } from './admin-post-returns-receive-items-req-schema-items-inner';


/**
 * The items details.
 */
export interface AdminPostReturnsReceiveItemsReqSchema { 
    /**
     * The items details.
     */
    items?: Array<AdminPostReturnsReceiveItemsReqSchemaItemsInner>;
}

