/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The import\'s summary.
 */
export interface AdminImportProductResponseSummary { 
    /**
     * The number of products that will be created by this import.
     */
    toCreate: number;
    /**
     * The number of products that will be updated by this import.
     */
    toUpdate: number;
}

