/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminUser } from './admin-user';


/**
 * The authenticated user\'s details.
 */
export interface AuthAdminSessionResponse { 
    user: AdminUser;
}

