/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The authentication\'s details.
 */
export interface AuthResponse { 
    /**
     * The JWT token used for registration or authentication.
     */
    token: string;
}

