/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The product type\'s details.
 */
export interface BaseProductType { 
    /**
     * The type\'s ID.
     */
    id: string;
    /**
     * The type\'s value.
     */
    value: string;
    /**
     * The date the type was created.
     */
    created_at: string;
    /**
     * The date the type was updated.
     */
    updated_at: string;
    /**
     * The date the type was deleted.
     */
    deleted_at?: string;
    /**
     * The type\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
}

