/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BaseRegionCountry } from './base-region-country';
import { AdminPaymentProvider } from './admin-payment-provider';


/**
 * The region\'s details.
 */
export interface BaseRegion { 
    /**
     * The region\'s ID.
     */
    id: string;
    /**
     * The region\'s name.
     */
    name: string;
    /**
     * The region\'s currency code.
     */
    currency_code: string;
    /**
     * The region\'s automatic taxes.
     */
    automatic_taxes?: boolean;
    /**
     * The region\'s countries.
     */
    countries?: Array<BaseRegionCountry>;
    /**
     * The region\'s payment providers.
     */
    payment_providers?: Array<AdminPaymentProvider>;
    /**
     * The region\'s metadata.
     */
    metadata?: object;
    /**
     * The region\'s created at.
     */
    created_at?: string;
    /**
     * The region\'s updated at.
     */
    updated_at?: string;
}

