/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The item\'s details.
 */
export interface BaseExchangeItem { 
    /**
     * The item\'s ID.
     */
    id: string;
    /**
     * The ID of the exchange this item belongs to.
     */
    exchange_id: string;
    /**
     * The ID of the order this item belongs to.
     */
    order_id: string;
    /**
     * The ID of the item in the order.
     */
    item_id: string;
    /**
     * The item\'s quantity.
     */
    quantity: number;
    /**
     * The item\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
    /**
     * The date the item was created.
     */
    created_at: string;
    /**
     * The date the item was updated.
     */
    updated_at: string;
}

