/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The adjustment\'s details.
 */
export interface BaseOrderLineItemAdjustment { 
    item: object;
    /**
     * The ID of the item this adjustment applies to.
     */
    item_id: string;
    /**
     * The adjustment\'s ID.
     */
    id: string;
    /**
     * The adjustment\'s code.
     */
    code?: string;
    /**
     * The adjustment\'s amount.
     */
    amount: number;
    /**
     * The ID of the associated order.
     */
    order_id: string;
    /**
     * The adjustment\'s description.
     */
    description?: string;
    /**
     * The ID of the promotion that this applies on the order\'s item.
     */
    promotion_id?: string;
    /**
     * The adjustment\'s provider ID.
     */
    provider_id?: string;
    /**
     * The date the adjustment was created.
     */
    created_at: string;
    /**
     * The date the adjustment was updated.
     */
    updated_at: string;
}

