/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The country\'s details.
 */
export interface BaseRegionCountry { 
    /**
     * The country\'s ID.
     */
    id: string;
    /**
     * The country\'s iso 2.
     */
    iso_2?: string;
    /**
     * The country\'s iso 3.
     */
    iso_3?: string;
    /**
     * The country\'s num code.
     */
    num_code?: string;
    /**
     * The country\'s name.
     */
    name?: string;
    /**
     * The country\'s display name.
     */
    display_name?: string;
}

