/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The details of a captured payment.
 */
export interface BaseCapture { 
    /**
     * The payment capture\'s ID.
     */
    id: string;
    /**
     * The captured amount.
     */
    amount: number;
    /**
     * The date the capture was created.
     */
    created_at: string;
    /**
     * The ID of the user that captured the payment.
     */
    created_by?: string;
    payment: object;
}

