/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The adjustment\'s details.
 */
export interface BaseShippingMethodAdjustment { 
    shipping_method: object;
    /**
     * The ID of the shipping method the adjustment is applied on.
     */
    shipping_method_id: string;
    /**
     * The adjustment\'s ID.
     */
    id: string;
    /**
     * The adjustment\'s code.
     */
    code?: string;
    /**
     * The adjustment\'s amount.
     */
    amount: number;
    /**
     * The ID of the associated cart.
     */
    cart_id: string;
    /**
     * The adjustment\'s description.
     */
    description?: string;
    /**
     * The ID of the promotion applied by this adjustment.
     */
    promotion_id?: string;
    /**
     * The adjustment\'s provider ID.
     */
    provider_id?: string;
    /**
     * The date the adjustment was created.
     */
    created_at: string;
    /**
     * The date the adjustment was updated.
     */
    updated_at: string;
}

