/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BaseClaimItemRawQuantity } from './base-claim-item-raw-quantity';


/**
 * The claim item\'s details.
 */
export interface BaseClaimItem { 
    /**
     * The claim item\'s ID.
     */
    id: string;
    /**
     * The ID of the claim this item belongs to.
     */
    claim_id: string;
    /**
     * The ID of the order this item belongs to.
     */
    order_id: string;
    /**
     * The ID of the item in the order.
     */
    item_id: string;
    /**
     * The quantity claimed.
     */
    quantity: number;
    /**
     * The claim\'s reason.
     */
    reason: BaseClaimItem.ReasonEnum;
    raw_quantity: BaseClaimItemRawQuantity;
    /**
     * The item\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
    /**
     * The date the claim was created.
     */
    created_at?: string;
    /**
     * The date the claim was updated.
     */
    updated_at?: string;
}
export namespace BaseClaimItem {
    export type ReasonEnum = 'missing_item' | 'wrong_item' | 'production_failure' | 'other';
    export const ReasonEnum = {
        MissingItem: 'missing_item' as ReasonEnum,
        WrongItem: 'wrong_item' as ReasonEnum,
        ProductionFailure: 'production_failure' as ReasonEnum,
        Other: 'other' as ReasonEnum
    };
}


