/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The campaign\'s budget.
 */
export interface CampaignResponseBudget { 
    /**
     * The budget\'s ID.
     */
    id: string;
    type: CampaignResponseBudget.TypeEnum;
    /**
     * The budget\'s currency code.
     */
    currency_code: string;
    /**
     * The budget\'s limit.
     */
    limit: number;
    /**
     * The budget\'s used.
     */
    used: number;
}
export namespace CampaignResponseBudget {
    export type TypeEnum = 'spend' | 'usage';
    export const TypeEnum = {
        Spend: 'spend' as TypeEnum,
        Usage: 'usage' as TypeEnum
    };
}


