/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerGroupInCustomerFiltersDeletedAt } from './customer-group-in-customer-filters-deleted-at';
import { CustomerGroupInCustomerFiltersId } from './customer-group-in-customer-filters-id';
import { CustomerGroupInCustomerFiltersCreatedAt } from './customer-group-in-customer-filters-created-at';
import { CustomerGroupInCustomerFiltersName } from './customer-group-in-customer-filters-name';
import { CustomerGroupInCustomerFiltersUpdatedAt } from './customer-group-in-customer-filters-updated-at';


/**
 * Filter by customer groups to get their associated customers.
 */
export interface CustomerGroupInCustomerFilters { 
    id: CustomerGroupInCustomerFiltersId;
    name: CustomerGroupInCustomerFiltersName;
    created_at: CustomerGroupInCustomerFiltersCreatedAt;
    updated_at: CustomerGroupInCustomerFiltersUpdatedAt;
    deleted_at: CustomerGroupInCustomerFiltersDeletedAt;
}

