/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The deletion\'s details.
 */
export interface DeleteSession200Response { 
    /**
     * Whether the session was deleted successfully.
     */
    success: boolean;
}

