/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Filter by the variants\' options.
 */
export interface GetProductsVariantsParameterOptions { 
    /**
     * The ID of the option to filter by.
     */
    option_id: string;
    /**
     * Filter by a value of the option.
     */
    value: string;
}

