/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * @type GetCollectionsCreatedAtParameterNotOneOfNot
 * @export
 */
export type GetCollectionsCreatedAtParameterNotOneOfNot = Array<string> | object | string;

