/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModelError { 
    /**
     * A slug code to indicate the type of the error.
     */
    code?: ModelError.CodeEnum;
    /**
     * Description of the error that occurred.
     */
    message?: string;
    /**
     * A slug indicating the type of the error.
     */
    type?: ModelError.TypeEnum;
}
export namespace ModelError {
    export type CodeEnum = 'invalid_state_error' | 'invalid_request_error' | 'api_error' | 'unknown_error';
    export const CodeEnum = {
        InvalidStateError: 'invalid_state_error' as CodeEnum,
        InvalidRequestError: 'invalid_request_error' as CodeEnum,
        ApiError: 'api_error' as CodeEnum,
        UnknownError: 'unknown_error' as CodeEnum
    };
    export type TypeEnum = 'QueryRunnerAlreadyReleasedError' | 'TransactionAlreadyStartedError' | 'TransactionNotStartedError' | 'conflict' | 'unauthorized' | 'payment_authorization_error' | 'duplicate_error' | 'not_allowed' | 'invalid_data' | 'not_found' | 'database_error' | 'unexpected_state' | 'invalid_argument' | 'unknown_error';
    export const TypeEnum = {
        QueryRunnerAlreadyReleasedError: 'QueryRunnerAlreadyReleasedError' as TypeEnum,
        TransactionAlreadyStartedError: 'TransactionAlreadyStartedError' as TypeEnum,
        TransactionNotStartedError: 'TransactionNotStartedError' as TypeEnum,
        Conflict: 'conflict' as TypeEnum,
        Unauthorized: 'unauthorized' as TypeEnum,
        PaymentAuthorizationError: 'payment_authorization_error' as TypeEnum,
        DuplicateError: 'duplicate_error' as TypeEnum,
        NotAllowed: 'not_allowed' as TypeEnum,
        InvalidData: 'invalid_data' as TypeEnum,
        NotFound: 'not_found' as TypeEnum,
        DatabaseError: 'database_error' as TypeEnum,
        UnexpectedState: 'unexpected_state' as TypeEnum,
        InvalidArgument: 'invalid_argument' as TypeEnum,
        UnknownError: 'unknown_error' as TypeEnum
    };
}


