/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderShippingMethodAdjustment } from './order-shipping-method-adjustment';
import { OrderShippingMethodTaxLine } from './order-shipping-method-tax-line';


/**
 * The shipping method\'s details.
 */
export interface OrderShippingMethod { 
    /**
     * The shipping method\'s ID.
     */
    id: string;
    /**
     * The ID of the order that the shipping method belongs to.
     */
    order_id: string;
    /**
     * The shipping method\'s name.
     */
    name: string;
    /**
     * The shipping method\'s description.
     */
    description?: string;
    /**
     * The shipping method\'s amount.
     */
    amount: number;
    /**
     * Whether the shipping method\'s amount includes taxes.
     */
    is_tax_inclusive: boolean;
    /**
     * The ID of the shipping option this method was created from.
     */
    shipping_option_id?: string;
    /**
     * The shipping method\'s data, useful for the fulfillment provider handling the fulfillment.
     */
    data?: object;
    /**
     * The shipping method\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
    /**
     * The shipping method\'s tax lines.
     */
    tax_lines?: Array<OrderShippingMethodTaxLine>;
    /**
     * The shipping method\'s adjustments.
     */
    adjustments?: Array<OrderShippingMethodAdjustment>;
    /**
     * The date the shipping method was created.
     */
    created_at: string;
    /**
     * The date the shipping method was updated.
     */
    updated_at: string;
    /**
     * The shipping method\'s total including taxes, excluding promotions.
     */
    original_total: number;
    /**
     * The shipping method\'s subtotal excluding taxes, including promotions.
     */
    original_subtotal: number;
    /**
     * The total taxes of the shipping method excluding promotions.
     */
    original_tax_total: number;
    /**
     * The shipping method\'s total including taxes and promotions.
     */
    total: number;
    /**
     * The shipping method\'s total excluding taxes, including promotions.
     */
    subtotal: number;
    /**
     * The total taxes of the shipping method, including promotions.
     */
    tax_total: number;
    /**
     * The shipping method\'s discount total.
     */
    discount_total: number;
    /**
     * The total taxes of the discount amount.
     */
    discount_tax_total: number;
}

