/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The credit line\'s details.
 */
export interface OrderCreditLine { 
    /**
     * The credit line\'s ID.
     */
    id: string;
    /**
     * The ID of the associated order.
     */
    order_id: string;
    order: object;
    /**
     * The table that this credit line references. For example, `payment_collection`.
     */
    reference: string;
    /**
     * The ID of the record in the referenced table. For example, `paycol_123`.
     */
    reference_id: string;
    /**
     * The credit line\'s metadata, can hold custom key-value pairs.
     */
    metadata: object;
    /**
     * The date the credit line was created.
     */
    created_at: string;
    /**
     * The date the credit line was updated.
     */
    updated_at: string;
}

