/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderChangeAction } from './order-change-action';
import { OrderExchange } from './order-exchange';
import { OrderClaim } from './order-claim';


/**
 * The order change\'s details.
 */
export interface OrderChange { 
    /**
     * The order change\'s ID.
     */
    id: string;
    /**
     * The order change\'s version. This will be the order\'s version when the change is applied.
     */
    version: number;
    /**
     * The order change\'s type.
     */
    change_type?: OrderChange.ChangeTypeEnum;
    /**
     * The ID of the order this change applies on.
     */
    order_id: string;
    /**
     * The ID of the associated return.
     */
    return_id: string;
    /**
     * The ID of the associated exchange.
     */
    exchange_id: string;
    /**
     * The ID of the associated claim.
     */
    claim_id: string;
    order: object;
    return_order: object;
    exchange: OrderExchange;
    claim: OrderClaim;
    /**
     * The order change\'s actions.
     */
    actions: Array<OrderChangeAction>;
    /**
     * The order change\'s status.
     */
    status: OrderChange.StatusEnum;
    /**
     * The ID of the user that requested the change.
     */
    requested_by: string;
    /**
     * The date the order change was requested.
     */
    requested_at: string;
    /**
     * The ID of the user that confirmed the order change.
     */
    confirmed_by: string;
    /**
     * The date the order change was confirmed.
     */
    confirmed_at: string;
    /**
     * The ID of the user that declined the order change.
     */
    declined_by: string;
    /**
     * The reason the order change was declined.
     */
    declined_reason: string;
    /**
     * The order change\'s metadata, can hold custom key-value pairs.
     */
    metadata: object;
    /**
     * The date the order change was declined.
     */
    declined_at: string;
    /**
     * The ID of the user that canceled the order change.
     */
    canceled_by: string;
    /**
     * The date the order change was canceled.
     */
    canceled_at: string;
    /**
     * The date the order change was created.
     */
    created_at: string;
    /**
     * The date the order change was updated.
     */
    updated_at: string;
}
export namespace OrderChange {
    export type ChangeTypeEnum = 'return' | 'exchange' | 'claim' | 'edit';
    export const ChangeTypeEnum = {
        Return: 'return' as ChangeTypeEnum,
        Exchange: 'exchange' as ChangeTypeEnum,
        Claim: 'claim' as ChangeTypeEnum,
        Edit: 'edit' as ChangeTypeEnum
    };
    export type StatusEnum = 'canceled' | 'requested' | 'pending' | 'confirmed' | 'declined';
    export const StatusEnum = {
        Canceled: 'canceled' as StatusEnum,
        Requested: 'requested' as StatusEnum,
        Pending: 'pending' as StatusEnum,
        Confirmed: 'confirmed' as StatusEnum,
        Declined: 'declined' as StatusEnum
    };
}


