/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StoreOrder } from './store-order';


/**
 * The created order\'s details.
 */
export interface PostCartsIdComplete200ResponseOneOf { 
    /**
     * The type of the returned object. In this case, the order is returned because the cart was completed successfully.
     */
    type: string;
    order: StoreOrder;
}

