/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The error\'s details.
 */
export interface PostCartsIdComplete200ResponseOneOf1Error { 
    /**
     * The error\'s message.
     */
    message: string;
    /**
     * The error\'s name.
     */
    name: string;
    /**
     * The error\'s type. Can be a [MedusaError type](https://docs.medusajs.com/v2/advanced-development/api-routes/errors#medusaerror-types) or `payment_authorization_error` or `payment_requires_more_error` for payment-related errors. 
     */
    type: string;
}

