/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Details on the reset password\'s status.
 */
export interface PostActorTypeAuthProviderUpdate200Response { 
    /**
     * Whether the password was reset successfully.
     */
    success: boolean;
}

