/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StoreCart } from './store-cart';


/**
 * The updated cart\'s details.
 */
export interface PostCartsId200Response { 
    cart: StoreCart;
}

