/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StoreCart } from './store-cart';
import { PostCartsIdComplete200ResponseOneOf1Error } from './post-carts-id-complete200-response-one-of1-error';


/**
 * The details of why the cart completion failed.
 */
export interface PostCartsIdComplete200ResponseOneOf1 { 
    /**
     * The type of the returned object. In this case, the cart is returned because an error has occurred.
     */
    type: string;
    cart: StoreCart;
    error: PostCartsIdComplete200ResponseOneOf1Error;
}

