/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthCallbackResponse } from './auth-callback-response';
import { AuthResponse } from './auth-response';


/**
 * @type PostActorTypeAuthProvider200Response
 * @export
 */
export type PostActorTypeAuthProvider200Response = AuthCallbackResponse | AuthResponse;

