/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StoreReturnItem } from './store-return-item';


/**
 * The return\'s details.
 */
export interface StoreReturn { 
    /**
     * The return\'s ID.
     */
    id: string;
    /**
     * The ID of the order this return is created for.
     */
    order_id: string;
    /**
     * The return\'s status.
     */
    status?: string;
    /**
     * The ID of the associated exchange.
     */
    exchange_id?: string;
    /**
     * The ID of the location the items are returned to.
     */
    location_id?: string;
    /**
     * The ID of the associated claim.
     */
    claim_id?: string;
    /**
     * The return\'s display ID.
     */
    display_id: number;
    /**
     * The return\'s refunded amount.
     */
    refund_amount?: number;
    /**
     * The return\'s items.
     */
    items: Array<StoreReturnItem>;
    /**
     * The date the return was received.
     */
    received_at: string;
    /**
     * The date the return was created.
     */
    created_at: string;
    /**
     * The date the return was updated.
     */
    canceled_at: string;
}

