/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StoreCartShippingMethodTaxLinesInner } from './store-cart-shipping-method-tax-lines-inner';
import { StoreCartShippingMethodAdjustmentsInner } from './store-cart-shipping-method-adjustments-inner';


/**
 * A cart\'s shipping method.
 */
export interface StoreCartShippingMethod { 
    /**
     * The shipping method\'s ID.
     */
    id: string;
    /**
     * The ID of the cart this shipping method belongs to.
     */
    cart_id: string;
    /**
     * The shipping method\'s name.
     */
    name: string;
    /**
     * The shipping method\'s description.
     */
    description?: string;
    /**
     * The shipping method\'s amount.
     */
    amount: number;
    /**
     * Whether the shipping method\'s amount is tax inclusive.
     */
    is_tax_inclusive: boolean;
    /**
     * The ID of the shipping option this method was created from.
     */
    shipping_option_id?: string;
    /**
     * The shipping method\'s data, useful for fulfillment handling by third-party services.
     */
    data?: object;
    /**
     * The shipping method\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
    /**
     * The shipping method\'s tax lines.
     */
    tax_lines?: Array<StoreCartShippingMethodTaxLinesInner>;
    /**
     * The shipping method\'s adjustments, such as applied promotions.
     */
    adjustments?: Array<StoreCartShippingMethodAdjustmentsInner>;
    /**
     * The date the shipping method was created.
     */
    created_at: string;
    /**
     * The date the shipping method was updated.
     */
    updated_at: string;
    /**
     * The shipping method\'s total including taxes, excluding promotions.
     */
    original_total: number;
    /**
     * The shipping method\'s total excluding taxes, including promotions.
     */
    original_subtotal: number;
    /**
     * The total taxes applied on the shipping method\'s amount including promotions.
     */
    original_tax_total: number;
    /**
     * The shipping method\'s total amount including taxes and promotions.
     */
    total: number;
    /**
     * The shipping method\'s total amount excluding taxes, including promotions.
     */
    subtotal: number;
    /**
     * The total taxes applied on the shipping method\'s amount including promotions.
     */
    tax_total: number;
    /**
     * The total amount discounted.
     */
    discount_total: number;
    /**
     * The taxes applied on the discounted amount.
     */
    discount_tax_total: number;
}

