/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The return\'s shipping details.
 */
export interface StoreCreateReturnShipping { 
    /**
     * The ID of the shipping option to use.
     */
    option_id: string;
    /**
     * The shipping\'s price.
     */
    price?: number;
}

