/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The origin price\'s details.
 */
export interface StoreCalculatedPriceOriginalPrice { 
    /**
     * The ID of the price.
     */
    id: string;
    /**
     * The ID of the associated price list.
     */
    price_list_id: string;
    /**
     * The price list\'s type. For example, `sale` or `override`.
     */
    price_list_type: string;
    /**
     * The minimum quantity required in the cart for the price to apply.
     */
    min_quantity: number;
    /**
     * The maximum quantity required in the cart for the price to apply.
     */
    max_quantity: number;
}

