/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StoreCreateReturnItem } from './store-create-return-item';
import { StoreCreateReturnShipping } from './store-create-return-shipping';


/**
 * The details of the return to create.
 */
export interface StoreCreateReturn { 
    /**
     * The ID of the order this return is created for.
     */
    order_id: string;
    /**
     * The return\'s items.
     */
    items: Array<StoreCreateReturnItem>;
    return_shipping: StoreCreateReturnShipping;
    /**
     * A note with more details about the return.
     */
    note?: string;
    /**
     * Whether to mark the return as received.
     */
    receive_now?: boolean;
    /**
     * The ID of the location that items are returned to.
     */
    location_id?: string;
}

