/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StoreShippingOptionType } from './store-shipping-option-type';
import { BaseFulfillmentProvider } from './base-fulfillment-provider';


/**
 * The shipping option\'s details.
 */
export interface StoreShippingOption { 
    /**
     * The shipping option\'s ID.
     */
    id: string;
    /**
     * The shipping option\'s name.
     */
    name: string;
    /**
     * The shipping option\'s price type. If it\'s `flat`, the price is fixed and is set in the `prices` property. If it\'s `calculated`, the price is calculated on checkout by the associated fulfillment provider.
     */
    price_type: StoreShippingOption.PriceTypeEnum;
    /**
     * The ID of the service zone the shipping option belongs to.
     */
    service_zone_id: string;
    /**
     * The ID of the fulfillment provider handling this option.
     */
    provider_id: string;
    provider: BaseFulfillmentProvider;
    /**
     * The ID of the shipping option\'s type.
     */
    shipping_option_type_id: string;
    type: StoreShippingOptionType;
    /**
     * The ID of the associated shipping profile.
     */
    shipping_profile_id: string;
    /**
     * The shipping option\'s amount.
     */
    amount: number;
    /**
     * Whether the amount includes taxes.
     */
    is_tax_inclusive: boolean;
    /**
     * The shipping option\'s data, useful for the provider handling fulfillment.
     */
    data: object;
    /**
     * The shipping option\'s metadata, can hold custom key-value pairs.
     */
    metadata: object;
}
export namespace StoreShippingOption {
    export type PriceTypeEnum = 'flat' | 'calculated';
    export const PriceTypeEnum = {
        Flat: 'flat' as PriceTypeEnum,
        Calculated: 'calculated' as PriceTypeEnum
    };
}


