/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StoreOrder } from './store-order';


/**
 * The order\'s details.
 */
export interface StoreOrderResponse { 
    order: StoreOrder;
}

