/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The return item\'s details.
 */
export interface StoreReturnItem { 
    /**
     * The item\'s ID.
     */
    id: string;
    /**
     * The item\'s quantity.
     */
    quantity: number;
    /**
     * The item\'s received quantity.
     */
    received_quantity: number;
    /**
     * The item\'s damaged quantity.
     */
    damaged_quantity: number;
    /**
     * The ID of the item\'s reason.
     */
    reason_id?: string;
    /**
     * A note with more details on why the item is returned.
     */
    note?: string;
    /**
     * The ID of the item in the order.
     */
    item_id: string;
    /**
     * The ID of the return this item belongs to.
     */
    return_id: string;
    /**
     * The item\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
}

