/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StoreOrderLineItemAdjustmentsInnerAllOfItem1 } from './store-order-line-item-adjustments-inner-all-of-item1';


/**
 * The adjustment\'s details.
 */
export interface StoreOrderLineItemAdjustmentsInner { 
    item: StoreOrderLineItemAdjustmentsInnerAllOfItem1;
    /**
     * The adjustment\'s item id.
     */
    item_id: string;
    /**
     * The adjustment\'s ID.
     */
    id: string;
    /**
     * The adjustment\'s code.
     */
    code?: string;
    /**
     * The adjustment\'s amount.
     */
    amount: number;
    /**
     * The adjustment\'s order id.
     */
    order_id: string;
    /**
     * The adjustment\'s description.
     */
    description?: string;
    /**
     * The adjustment\'s promotion id.
     */
    promotion_id?: string;
    /**
     * The adjustment\'s provider id.
     */
    provider_id?: string;
    /**
     * The adjustment\'s created at.
     */
    created_at: string;
    /**
     * The adjustment\'s updated at.
     */
    updated_at: string;
}

