/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StoreCartShippingOption } from './store-cart-shipping-option';


/**
 * The shipping option\'s details.
 */
export interface StoreShippingOptionListResponse { 
    /**
     * The shipping option\'s shipping options.
     */
    shipping_options: Array<StoreCartShippingOption>;
}

