/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The details to update in the line item.
 */
export interface StoreUpdateCartLineItem { 
    /**
     * The item\'s quantity.
     */
    quantity: number;
    /**
     * The item\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
}

