/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The tag\'s details.
 */
export interface StoreProductTag { 
    /**
     * The tag\'s ID.
     */
    id: string;
    /**
     * The tag\'s value.
     */
    value: string;
    /**
     * The date the tag was created.
     */
    created_at: string;
    /**
     * The date the tag was updated.
     */
    updated_at: string;
    /**
     * The date the tag was deleted.
     */
    deleted_at?: string;
    /**
     * The tag\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
}

