/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The shipping option type\'s details.
 */
export interface StoreShippingOptionType { 
    /**
     * The type\'s ID.
     */
    id: string;
    /**
     * The type\'s label.
     */
    label: string;
    /**
     * The type\'s description.
     */
    description: string;
    /**
     * The type\'s code.
     */
    code: string;
    /**
     * The ID of the associated shipping option.
     */
    shipping_option_id: string;
    /**
     * The date the type was created.
     */
    created_at: string;
    /**
     * The date the type was updated.
     */
    updated_at: string;
    /**
     * The date the type was deleted.
     */
    deleted_at: string;
}

