/**
 * Medusa Storefront API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StoreCalculatedPrice } from './store-calculated-price';
import { StoreCartShippingOptionProvider } from './store-cart-shipping-option-provider';
import { StorePrice } from './store-price';
import { StoreCartShippingOptionType } from './store-cart-shipping-option-type';


/**
 * The shipping option\'s details.
 */
export interface StoreCartShippingOption {
    /**
     * The shipping option\'s ID.
     */
    id: string;
    /**
     * The shipping option\'s name.
     */
    name: string;
    /**
     * The shipping option\'s price type. If it\'s `flat`, the price is fixed and is set in the `prices` property. If it\'s `calculated`, the price is calculated on checkout-page by the associated fulfillment provider.
     */
    price_type: StoreCartShippingOption.PriceTypeEnum;
    /**
     * The ID of the service zone the shipping option belongs to.
     */
    service_zone_id: string;
    /**
     * The ID of the fulfillment provider handling this option.
     */
    provider_id: string;
    provider: StoreCartShippingOptionProvider;
    type: StoreCartShippingOptionType;
    /**
     * The ID of the associated shipping profile.
     */
    shipping_profile_id: string;
    /**
     * The shipping option\'s amount.
     */
    amount: number;
    /**
     * The shipping option\'s data, useful for the provider handling fulfillment.
     */
    data: object;
    /**
     * The shipping option\'s prices.
     */
    prices: Array<StorePrice>;
    calculated_price: StoreCalculatedPrice;
}
export namespace StoreCartShippingOption {
    export type PriceTypeEnum = 'flat' | 'calculated';
    export const PriceTypeEnum = {
        Flat: 'flat' as PriceTypeEnum,
        Calculated: 'calculated' as PriceTypeEnum
    };
}


