/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StorePriceRule } from './store-price-rule';


/**
 * The price\'s details.
 */
export interface StorePrice { 
    /**
     * The price\'s ID.
     */
    id: string;
    /**
     * The price\'s ISO 2 currency code.
     */
    currency_code: string;
    /**
     * The price\'s amount.
     */
    amount: number;
    /**
     * The minimum quantity required in the cart for the price to apply.
     */
    min_quantity: number;
    /**
     * The maximum quantity required in the cart for the price to apply.
     */
    max_quantity: number;
    /**
     * The price\'s rules.
     */
    price_rules?: Array<StorePriceRule>;
}

