/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BaseRegionCountry } from './base-region-country';
import { AdminPaymentProvider } from './admin-payment-provider';


/**
 * The region\'s details.
 */
export interface StoreRegion { 
    /**
     * The region\'s ID.
     */
    id: string;
    /**
     * The region\'s name.
     */
    name: string;
    /**
     * The region\'s currency code.
     */
    currency_code: string;
    /**
     * Whether taxes are calculated automatically during checkout for carts that belong to this region.
     */
    automatic_taxes?: boolean;
    /**
     * The region\'s countries.
     */
    countries?: Array<BaseRegionCountry>;
    /**
     * The region\'s payment providers.
     */
    payment_providers?: Array<AdminPaymentProvider>;
    /**
     * The region\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
    /**
     * The date the region was created.
     */
    created_at?: string;
    /**
     * The date the region was updated.
     */
    updated_at?: string;
}

