/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The promotion\'s details.
 */
export interface StoreCartAddPromotion { 
    /**
     * Promotion codes to add to the cart.
     */
    promo_codes: Array<string>;
}

