/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StoreCurrency } from './store-currency';


/**
 * The currency\'s details.
 */
export interface StoreCurrencyResponse { 
    currency: StoreCurrency;
}

