/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StoreOrderLineItemTaxLinesInnerAllOfItem1Detail { 
    /**
     * The detail\'s ID.
     */
    id: string;
    /**
     * The detail\'s item id.
     */
    item_id: string;
    /**
     * The detail\'s item.
     */
    item: object;
    /**
     * The detail\'s quantity.
     */
    quantity: number;
    /**
     * The detail\'s fulfilled quantity.
     */
    fulfilled_quantity: number;
    /**
     * The detail\'s delivered quantity.
     */
    delivered_quantity: number;
    /**
     * The detail\'s shipped quantity.
     */
    shipped_quantity: number;
    /**
     * The detail\'s return requested quantity.
     */
    return_requested_quantity: number;
    /**
     * The detail\'s return received quantity.
     */
    return_received_quantity: number;
    /**
     * The detail\'s return dismissed quantity.
     */
    return_dismissed_quantity: number;
    /**
     * The detail\'s written off quantity.
     */
    written_off_quantity: number;
    /**
     * The detail\'s metadata.
     */
    metadata: object;
    /**
     * The detail\'s created at.
     */
    created_at: string;
    /**
     * The detail\'s updated at.
     */
    updated_at: string;
}

