/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StoreCustomerAddress } from './store-customer-address';


/**
 * The customer\'s details.
 */
export interface StoreCustomer { 
    /**
     * The customer\'s ID.
     */
    id: string;
    /**
     * The customer\'s email.
     */
    email: string;
    /**
     * The ID of the address used for billing by default.
     */
    default_billing_address_id: string;
    /**
     * The ID of the address used for shipping by default.
     */
    default_shipping_address_id: string;
    /**
     * The customer\'s company name.
     */
    company_name: string;
    /**
     * The customer\'s first name.
     */
    first_name: string;
    /**
     * The customer\'s last name.
     */
    last_name: string;
    /**
     * The customer\'s addresses.
     */
    addresses: Array<StoreCustomerAddress>;
    /**
     * The customer\'s phone.
     */
    phone?: string;
    /**
     * The customer\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
    /**
     * The date the customer was created.
     */
    created_at?: string;
    /**
     * The date the customer was updated.
     */
    updated_at?: string;
    /**
     * The date the customer was deleted.
     */
    deleted_at?: string;
}

