/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StorePaymentCollection } from './store-payment-collection';


/**
 * The payment collection\'s details.
 */
export interface StorePaymentCollectionResponse { 
    payment_collection: StorePaymentCollection;
}

