/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StoreOrderShippingMethodTaxLinesInnerAllOfShippingMethod1Detail { 
    /**
     * The detail\'s ID.
     */
    id: string;
    /**
     * The detail\'s shipping method id.
     */
    shipping_method_id: string;
    /**
     * The detail\'s shipping method.
     */
    shipping_method: object;
    /**
     * The detail\'s claim id.
     */
    claim_id?: string;
    /**
     * The detail\'s exchange id.
     */
    exchange_id?: string;
    /**
     * The detail\'s return id.
     */
    return_id?: string;
    /**
     * The detail\'s created at.
     */
    created_at: string;
    /**
     * The detail\'s updated at.
     */
    updated_at: string;
}

