/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StoreProductCategory } from './store-product-category';


/**
 * The product category\'s details.
 */
export interface StoreProductCategoryResponse { 
    product_category: StoreProductCategory;
}

