/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StoreOrderShippingMethodAdjustmentsInnerAllOfShippingMethod1 } from './store-order-shipping-method-adjustments-inner-all-of-shipping-method1';


/**
 * The adjustment\'s adjustments.
 */
export interface StoreOrderShippingMethodAdjustmentsInner { 
    shipping_method: StoreOrderShippingMethodAdjustmentsInnerAllOfShippingMethod1;
    /**
     * The adjustment\'s shipping method id.
     */
    shipping_method_id: string;
    /**
     * The adjustment\'s ID.
     */
    id: string;
    /**
     * The adjustment\'s code.
     */
    code?: string;
    /**
     * The adjustment\'s amount.
     */
    amount: number;
    /**
     * The adjustment\'s order id.
     */
    order_id: string;
    /**
     * The adjustment\'s description.
     */
    description?: string;
    /**
     * The adjustment\'s promotion id.
     */
    promotion_id?: string;
    /**
     * The adjustment\'s provider id.
     */
    provider_id?: string;
    /**
     * The adjustment\'s created at.
     */
    created_at: string;
    /**
     * The adjustment\'s updated at.
     */
    updated_at: string;
}

