/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StoreCalculatedPriceOriginalPrice } from './store-calculated-price-original-price';
import { StoreCalculatedPriceCalculatedPrice } from './store-calculated-price-calculated-price';


/**
 * The shipping option\'s calculated price.
 */
export interface StoreCalculatedPrice { 
    /**
     * The ID of the price set from which the price was selected.
     */
    id: string;
    /**
     * Whether the calculated price belongs to a price list.
     */
    is_calculated_price_price_list?: boolean;
    /**
     * Whether the calculated price is tax inclusive.
     */
    is_calculated_price_tax_inclusive?: boolean;
    /**
     * The amount of the calculated price, or `null` if there isn\'t a calculated price. This is the amount shown to the customer.
     */
    calculated_amount: number;
    /**
     * The `calculated_amount` with taxes applied.
     */
    calculated_amount_with_tax?: number;
    /**
     * The `calculated_amount` without taxes applied.
     */
    calculated_amount_without_tax?: number;
    /**
     * Whether the original price belongs to a price list.
     */
    is_original_price_price_list?: boolean;
    /**
     * Whether the original price is tax inclusive.
     */
    is_original_price_tax_inclusive?: boolean;
    /**
     * The amount of the original price, or `null` if there isn\'t an original price. This amount is useful to compare with the `calculated_amount`, such as to check for discounted value.
     */
    original_amount: number;
    /**
     * The currency code of the calculated price, or `null` if there isn\'t a calculated price.
     */
    currency_code: string;
    calculated_price?: StoreCalculatedPriceCalculatedPrice;
    original_price?: StoreCalculatedPriceOriginalPrice;
}

