/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StoreCartPromotionApplicationMethod } from './store-cart-promotion-application-method';


/**
 * The promotion\'s promotions.
 */
export interface StoreCartPromotion { 
    /**
     * The promotion\'s ID.
     */
    id: string;
    /**
     * The promotion\'s code.
     */
    code?: string;
    /**
     * The promotion\'s is automatic.
     */
    is_automatic?: boolean;
    application_method?: StoreCartPromotionApplicationMethod;
}

