/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The return reason\'s details.
 */
export interface StoreReturnReason { 
    /**
     * The return reason\'s ID.
     */
    id: string;
    /**
     * The return reason\'s value.
     */
    value: string;
    /**
     * The return reason\'s label.
     */
    label: string;
    /**
     * The return reason\'s description.
     */
    description?: string;
    /**
     * The return reason\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
    /**
     * The date the return reason was created.
     */
    created_at: string;
    /**
     * The date the return reason was updated.
     */
    updated_at: string;
}

