/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StoreProductImage } from './store-product-image';
import { StoreProductVariant } from './store-product-variant';
import { StoreProductType } from './store-product-type';
import { StoreProductTag } from './store-product-tag';
import { StoreProductOption } from './store-product-option';
import { StoreCollection } from './store-collection';


/**
 * The product\'s details.
 */
export interface StoreProduct { 
    /**
     * The product\'s categories.
     */
    categories?: Array<object>;
    type?: StoreProductType;
    /**
     * The product\'s length.
     */
    length: number;
    /**
     * The product\'s title.
     */
    title: string;
    /**
     * The product\'s status.
     */
    status: StoreProduct.StatusEnum;
    /**
     * The product\'s options.
     */
    options: Array<StoreProductOption>;
    /**
     * The product\'s description.
     */
    description: string;
    /**
     * The product\'s ID.
     */
    id: string;
    /**
     * The product\'s metadata, can hold custom key-value pairs.
     */
    metadata?: object;
    /**
     * The date the product was created.
     */
    created_at: string;
    /**
     * The date the product was updated.
     */
    updated_at: string;
    /**
     * The product\'s variants.
     */
    variants: Array<StoreProductVariant>;
    /**
     * The product\'s handle.
     */
    handle: string;
    /**
     * The product\'s subtitle.
     */
    subtitle: string;
    /**
     * Whether the product is a gift card.
     */
    is_giftcard: boolean;
    /**
     * The product\'s thumbnail URL.
     */
    thumbnail: string;
    /**
     * The product\'s width.
     */
    width: number;
    /**
     * The product\'s weight.
     */
    weight: number;
    /**
     * The product\'s height.
     */
    height: number;
    /**
     * The product\'s origin country.
     */
    origin_country: string;
    /**
     * The product\'s HS code.
     */
    hs_code: string;
    /**
     * The product\'s MID code.
     */
    mid_code: string;
    /**
     * The product\'s material.
     */
    material: string;
    collection?: StoreCollection;
    /**
     * The ID of the collection that the product belongs to.
     */
    collection_id: string;
    /**
     * The ID of the product\'s type.
     */
    type_id: string;
    /**
     * The product\'s tags.
     */
    tags?: Array<StoreProductTag>;
    /**
     * The product\'s images.
     */
    images: Array<StoreProductImage>;
    /**
     * Whether the product can be discounted.
     */
    discountable: boolean;
    /**
     * The ID of the product in an external service or system.
     */
    external_id: string;
    /**
     * The date the product was deleted.
     */
    deleted_at: string;
}
export namespace StoreProduct {
    export type StatusEnum = 'draft' | 'proposed' | 'published' | 'rejected';
    export const StatusEnum = {
        Draft: 'draft' as StatusEnum,
        Proposed: 'proposed' as StatusEnum,
        Published: 'published' as StatusEnum,
        Rejected: 'rejected' as StatusEnum
    };
}


