/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The details of accepting the order transfer.
 */
export interface StoreAcceptOrderTransfer { 
    /**
     * The order transfer\'s token issued when the transfer was requested.
     */
    token: string;
}

