/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateAddress } from './create-address';
import { UpdateAddress } from './update-address';


/**
 * @type UpdateCartDataBillingAddress
 * @export
 */
export type UpdateCartDataBillingAddress = CreateAddress | UpdateAddress;

