/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The error\'s details.
 */
export interface WorkflowExecutionContextErrorsInner { 
    /**
     * The error\'s details.
     */
    error: object;
    /**
     * The error\'s action.
     */
    action: string;
    /**
     * The error\'s handler type.
     */
    handlerType: string;
}

