/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkflowExecutionContextDataInvokeValueOutput } from './workflow-execution-context-data-invoke-value-output';


export interface WorkflowExecutionContextDataInvokeValue { 
    output?: WorkflowExecutionContextDataInvokeValueOutput;
}

