export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './carts.service';
import { CartsService } from './carts.service';
export * from './carts.serviceInterface';
export * from './collections.service';
import { CollectionsService } from './collections.service';
export * from './collections.serviceInterface';
export * from './currencies.service';
import { CurrenciesService } from './currencies.service';
export * from './currencies.serviceInterface';
export * from './customers.service';
import { CustomersService } from './customers.service';
export * from './customers.serviceInterface';
export * from './orders.service';
import { OrdersService } from './orders.service';
export * from './orders.serviceInterface';
export * from './payment-collections.service';
import { PaymentCollectionsService } from './payment-collections.service';
export * from './payment-collections.serviceInterface';
export * from './payment-providers.service';
import { PaymentProvidersService } from './payment-providers.service';
export * from './payment-providers.serviceInterface';
export * from './product-categories.service';
import { ProductCategoriesService } from './product-categories.service';
export * from './product-categories.serviceInterface';
export * from './product-tags.service';
import { ProductTagsService } from './product-tags.service';
export * from './product-tags.serviceInterface';
export * from './product-types.service';
import { ProductTypesService } from './product-types.service';
export * from './product-types.serviceInterface';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './products.serviceInterface';
export * from './regions.service';
import { RegionsService } from './regions.service';
export * from './regions.serviceInterface';
export * from './return.service';
import { ReturnService } from './return.service';
export * from './return.serviceInterface';
export * from './return-reasons.service';
import { ReturnReasonsService } from './return-reasons.service';
export * from './return-reasons.serviceInterface';
export * from './shipping-options.service';
import { ShippingOptionsService } from './shipping-options.service';
export * from './shipping-options.serviceInterface';
export const APIS = [AuthService, CartsService, CollectionsService, CurrenciesService, CustomersService, OrdersService, PaymentCollectionsService, PaymentProvidersService, ProductCategoriesService, ProductTagsService, ProductTypesService, ProductsService, RegionsService, ReturnService, ReturnReasonsService, ShippingOptionsService];
