/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GetCurrenciesCodeParameter } from '../model/models';
import { StoreCurrencyListResponse } from '../model/models';
import { StoreCurrencyResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CurrenciesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * List Currencies
     * Retrieve a list of currencies. The currencies can be filtered by fields such as &#x60;code&#x60;. The currencies can also be sorted or paginated.
     * @param xPublishableApiKey Publishable API Key created in the Medusa Admin.
     * @param fields Comma-separated fields that should be included in the returned data. if a field is prefixed with &#x60;+&#x60; it will be added to the default fields, using &#x60;-&#x60; will remove it from the default fields. without prefix it will replace the entire default fields.
     * @param offset The number of items to skip when retrieving a list.
     * @param limit Limit the number of items returned in the list.
     * @param order The field to sort the data by. By default, the sort order is ascending. To change the order to descending, prefix the field name with &#x60;-&#x60;.
     * @param q Search term to filter the currency\&#39;s searchable properties.
     * @param code 
     * @param $and Join query parameters with an AND condition. Each object\&#39;s content is the same type as the expected query parameters.
     * @param $or Join query parameters with an OR condition. Each object\&#39;s content is the same type as the expected query parameters.
     */
    getCurrencies(xPublishableApiKey: string, fields?: string, offset?: number, limit?: number, order?: string, q?: string, code?: GetCurrenciesCodeParameter, $and?: Array<object>, $or?: Array<object>, extraHttpRequestParams?: any): Observable<StoreCurrencyListResponse>;

    /**
     * Get a Currency
     * Retrieve a currency by its code. You can expand the currency\&#39;s relations or select the fields that should be returned.
     * @param code The currency\&#39;s code.
     * @param xPublishableApiKey Publishable API Key created in the Medusa Admin.
     * @param fields Comma-separated fields that should be included in the returned data. if a field is prefixed with &#x60;+&#x60; it will be added to the default fields, using &#x60;-&#x60; will remove it from the default fields. without prefix it will replace the entire default fields.
     */
    getCurrenciesCode(code: string, xPublishableApiKey: string, fields?: string, extraHttpRequestParams?: any): Observable<StoreCurrencyResponse>;

}
