/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GetProductTagsCreatedAtParameter } from '../model/models';
import { GetProductTagsIdParameter } from '../model/models';
import { GetProductTagsUpdatedAtParameter } from '../model/models';
import { GetProductTagsValueParameter } from '../model/models';
import { StoreProductTagListResponse } from '../model/models';
import { StoreProductTagResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ProductTagsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * List Product Tags
     * Retrieve a list of product tags. The product tags can be filtered by fields such as &#x60;id&#x60;. The product tags can also be sorted or paginated.
     * @param xPublishableApiKey Publishable API Key created in the Medusa Admin.
     * @param fields Comma-separated fields that should be included in the returned data. if a field is prefixed with &#x60;+&#x60; it will be added to the default fields, using &#x60;-&#x60; will remove it from the default fields. without prefix it will replace the entire default fields.
     * @param offset The number of items to skip when retrieving a list.
     * @param limit Limit the number of items returned in the list.
     * @param order The field to sort the data by. By default, the sort order is ascending. To change the order to descending, prefix the field name with &#x60;-&#x60;.
     * @param $and Join query parameters with an AND condition. Each object\&#39;s content is the same type as the expected query parameters.
     * @param $or Join query parameters with an OR condition. Each object\&#39;s content is the same type as the expected query parameters.
     * @param q Query to search product tag\&#39;s searchable fields.
     * @param id 
     * @param value 
     * @param createdAt Filter by the tag\&#39;s creation date.
     * @param updatedAt Filter by the tag\&#39;s update date.
     */
    getProductTags(xPublishableApiKey: string, fields?: string, offset?: number, limit?: number, order?: string, $and?: Array<object>, $or?: Array<object>, q?: string, id?: GetProductTagsIdParameter, value?: GetProductTagsValueParameter, createdAt?: GetProductTagsCreatedAtParameter, updatedAt?: GetProductTagsUpdatedAtParameter, extraHttpRequestParams?: any): Observable<StoreProductTagListResponse>;

    /**
     * Get a Product Tag
     * Retrieve a product tag by its ID. You can expand the product tag\&#39;s relations or select the fields that should be returned.
     * @param id The product tag\&#39;s ID.
     * @param xPublishableApiKey Publishable API Key created in the Medusa Admin.
     * @param fields Comma-separated fields that should be included in the returned data. if a field is prefixed with &#x60;+&#x60; it will be added to the default fields, using &#x60;-&#x60; will remove it from the default fields. without prefix it will replace the entire default fields.
     */
    getProductTagsId(id: string, xPublishableApiKey: string, fields?: string, extraHttpRequestParams?: any): Observable<StoreProductTagResponse>;

}
