/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { StoreCreateReturn } from '../model/models';
import { StoreReturnResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ReturnServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create Return
     * Create a return for an order\&#39;s items. The admin receives the return and process it from their side.
     * @param xPublishableApiKey Publishable API Key created in the Medusa Admin.
     * @param storeCreateReturn 
     */
    postReturn(xPublishableApiKey: string, storeCreateReturn?: StoreCreateReturn, extraHttpRequestParams?: any): Observable<StoreReturnResponse>;

}
