/**
 * Medusa Storefront API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GetReturnReasons200Response } from '../model/models';
import { StoreReturnReasonResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ReturnReasonsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * List Return Reasons
     * Retrieve a list of return reasons. The return reasons can be sorted or paginated.
     * @param xPublishableApiKey Publishable API Key created in the Medusa Admin.
     * @param fields Comma-separated fields that should be included in the returned data. if a field is prefixed with &#x60;+&#x60; it will be added to the default fields, using &#x60;-&#x60; will remove it from the default fields. without prefix it will replace the entire default fields.
     * @param offset The number of items to skip when retrieving a list.
     * @param limit Limit the number of items returned in the list.
     * @param order The field to sort the data by. By default, the sort order is ascending. To change the order to descending, prefix the field name with &#x60;-&#x60;.
     */
    getReturnReasons(xPublishableApiKey: string, fields?: string, offset?: number, limit?: number, order?: string, extraHttpRequestParams?: any): Observable<GetReturnReasons200Response>;

    /**
     * Get a Return Reason
     * Retrieve a return reason by its ID. You can expand the return reason\&#39;s relations or select the fields that should be returned.
     * @param id The return reason\&#39;s ID.
     * @param xPublishableApiKey Publishable API Key created in the Medusa Admin.
     * @param fields Comma-separated fields that should be included in the returned data. if a field is prefixed with &#x60;+&#x60; it will be added to the default fields, using &#x60;-&#x60; will remove it from the default fields. without prefix it will replace the entire default fields.
     */
    getReturnReasonsId(id: string, xPublishableApiKey: string, fields?: string, extraHttpRequestParams?: any): Observable<StoreReturnReasonResponse>;

}
